require("Font8x12").add(Graphics);

Graphics.prototype.setFontAnton = function(scale) {
  // Actual height 69 (68 - 0)
  g.setFontCustom(atob("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/gAAAAAAAAAAf/gAAAAAAAAAAf/gAAAAAAAAAAf/gAAAAAAAAAAf/gAAAAAAAAAAf/gAAAAAAAAAAf/gAAAAAAAAAAf/gAAAAAAAAAAf/gAAAAAAAAAAf/gAAAAAAAAAAf/gAAAAAAAAAAf/gAAAAAAAAAAf/gAAAAAAAAAAf/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgAAAAAAAAAAA/gAAAAAAAAAAP/gAAAAAAAAAH//gAAAAAAAAB///gAAAAAAAAf///gAAAAAAAP////gAAAAAAD/////gAAAAAA//////gAAAAAP//////gAAAAH///////gAAAB////////gAAAf////////gAAP/////////gAD//////////AA//////////gAA/////////4AAA////////+AAAA////////gAAAA///////wAAAAA//////8AAAAAA//////AAAAAAA/////gAAAAAAA////4AAAAAAAA///+AAAAAAAAA///gAAAAAAAAA//wAAAAAAAAAA/8AAAAAAAAAAA/AAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//////AAAAAB///////8AAAAH////////AAAAf////////wAAA/////////4AAB/////////8AAD/////////+AAH//////////AAP//////////gAP//////////gAP//////////gAf//////////wAf//////////wAf//////////wAf//////////wA//8AAAAAB//4A//wAAAAAAf/4A//gAAAAAAP/4A//gAAAAAAP/4A//gAAAAAAP/4A//wAAAAAAf/4A///////////4Af//////////wAf//////////wAf//////////wAf//////////wAP//////////gAP//////////gAH//////////AAH//////////AAD/////////+AAB/////////8AAA/////////4AAAP////////gAAAD///////+AAAAAf//////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/gAAAAAAAAAAP/gAAAAAAAAAAf/gAAAAAAAAAAf/gAAAAAAAAAAf/AAAAAAAAAAA//AAAAAAAAAAA/+AAAAAAAAAAB/8AAAAAAAAAAD//////////gAH//////////gAP//////////gA///////////gA///////////gA///////////gA///////////gA///////////gA///////////gA///////////gA///////////gA///////////gA///////////gA///////////gA///////////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/4AAAAB/gAAD//4AAAAf/gAAP//4AAAB//gAA///4AAAH//gAB///4AAAf//gAD///4AAA///gAH///4AAD///gAP///4AAH///gAP///4AAP///gAf///4AAf///gAf///4AB////gAf///4AD////gA////4AH////gA////4Af////gA////4A/////gA//wAAB/////gA//gAAH/////gA//gAAP/////gA//gAA///8//gA//gAD///w//gA//wA////g//gA////////A//gA///////8A//gA///////4A//gAf//////wA//gAf//////gA//gAf/////+AA//gAP/////8AA//gAP/////4AA//gAH/////gAA//gAD/////AAA//gAB////8AAA//gAA////wAAA//gAAP///AAAA//gAAD//8AAAA//gAAAP+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/+AAAAAD/wAAB//8AAAAP/wAAB///AAAA//wAAB///wAAB//wAAB///4AAD//wAAB///8AAH//wAAB///+AAP//wAAB///+AAP//wAAB////AAf//wAAB////AAf//wAAB////gAf//wAAB////gA///wAAB////gA///wAAB////gA///w//AAf//wA//4A//AAA//wA//gA//AAAf/wA//gB//gAAf/wA//gB//gAAf/wA//gD//wAA//wA//wH//8AB//wA///////////gA///////////gA///////////gA///////////gAf//////////AAf//////////AAP//////////AAP/////////+AAH/////////8AAH///+/////4AAD///+f////wAAA///8P////gAAAf//4H///+AAAAH//gB///wAAAAAP4AAH/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/wAAAAAAAAAA//wAAAAAAAAAP//wAAAAAAAAB///wAAAAAAAAf///wAAAAAAAH////wAAAAAAA/////wAAAAAAP/////wAAAAAB//////wAAAAAf//////wAAAAH///////wAAAA////////wAAAP////////wAAA///////H/wAAA//////wH/wAAA/////8AH/wAAA/////AAH/wAAA////gAAH/wAAA///4AAAH/wAAA//+AAAAH/wAAA///////////gA///////////gA///////////gA///////////gA///////////gA///////////gA///////////gA///////////gA///////////gA///////////gA///////////gA///////////gA///////////gA///////////gAAAAAAAAH/4AAAAAAAAAAH/wAAAAAAAAAAH/wAAAAAAAAAAH/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//8AAA/////+B///AAA/////+B///wAA/////+B///4AA/////+B///8AA/////+B///8AA/////+B///+AA/////+B////AA/////+B////AA/////+B////AA/////+B////gA/////+B////gA/////+B////gA/////+A////gA//gP/gAAB//wA//gf/AAAA//wA//gf/AAAAf/wA//g//AAAAf/wA//g//AAAA//wA//g//gAAA//wA//g//+AAP//wA//g////////gA//g////////gA//g////////gA//g////////gA//g////////AA//gf///////AA//gf//////+AA//gP//////+AA//gH//////8AA//gD//////4AA//gB//////wAA//gA//////AAAAAAAH////8AAAAAAAA////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//////gAAAAB///////+AAAAH////////gAAAf////////4AAB/////////8AAD/////////+AAH//////////AAH//////////gAP//////////gAP//////////gAf//////////wAf//////////wAf//////////wAf//////////wAf//////////4A//wAD/4AAf/4A//gAH/wAAP/4A//gAH/wAAP/4A//gAP/wAAP/4A//gAP/4AAf/4A//wAP/+AD//4A///wP//////4Af//4P//////wAf//4P//////wAf//4P//////wAf//4P//////wAP//4P//////gAP//4H//////gAH//4H//////AAH//4D/////+AAD//4D/////8AAB//4B/////4AAA//4A/////wAAAP/4AP////AAAAB/4AD///4AAAAAAAAAH/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//AAAAAAAAAAA//gAAAAAAAAAA//gAAAAAAAAAA//gAAAAAAADgA//gAAAAAAP/gA//gAAAAAH//gA//gAAAAB///gA//gAAAAP///gA//gAAAD////gA//gAAAf////gA//gAAB/////gA//gAAP/////gA//gAB//////gA//gAH//////gA//gA///////gA//gD///////gA//gf///////gA//h////////gA//n////////gA//////////gAA/////////AAAA////////wAAAA///////4AAAAA///////AAAAAA//////4AAAAAA//////AAAAAAA/////4AAAAAAA/////AAAAAAAA////8AAAAAAAA////gAAAAAAAA///+AAAAAAAAA///4AAAAAAAAA///AAAAAAAAAA//4AAAAAAAAAA/+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//gB///wAAAAP//4H///+AAAA///8P////gAAB///+f////4AAD///+/////8AAH/////////+AAH//////////AAP//////////gAP//////////gAf//////////gAf//////////wAf//////////wAf//////////wA///////////wA//4D//wAB//4A//wB//gAA//4A//gA//gAAf/4A//gA//AAAf/4A//gA//gAAf/4A//wB//gAA//4A///P//8AH//4Af//////////wAf//////////wAf//////////wAf//////////wAf//////////gAP//////////gAP//////////AAH//////////AAD/////////+AAD///+/////8AAB///8f////wAAAf//4P////AAAAH//wD///8AAAAA/+AAf//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH//gAAAAAAAAB///+AA/+AAAAP////gA//wAAAf////wA//4AAB/////4A//8AAD/////8A//+AAD/////+A///AAH/////+A///AAP//////A///gAP//////A///gAf//////A///wAf//////A///wAf//////A///wAf//////A///wA///////AB//4A//4AD//AAP/4A//gAB//AAP/4A//gAA//AAP/4A//gAA/+AAP/4A//gAB/8AAP/4A//wAB/8AAf/4Af//////////wAf//////////wAf//////////wAf//////////wAf//////////wAP//////////gAP//////////gAH//////////AAH/////////+AAD/////////8AAB/////////4AAAf////////wAAAP////////AAAAB///////4AAAAAD/////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/AAB/8AAAAAA//AAD/8AAAAAA//AAD/8AAAAAA//AAD/8AAAAAA//AAD/8AAAAAA//AAD/8AAAAAA//AAD/8AAAAAA//AAD/8AAAAAA//AAD/8AAAAAA//AAD/8AAAAAA//AAD/8AAAAAA//AAD/8AAAAAA//AAD/8AAAAAA//AAD/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="), 46, atob("EiAnGicnJycnJycnEw=="), 78 + (scale << 8) + (1 << 16));
};

Graphics.prototype.setFontAntonSmall = function(scale) {
  // Actual height 53 (52 - 0)
  g.setFontCustom(atob("AAAAAAAAAAAAAAAAAAAAAAAAAAf8AAAAAAAAf8AAAAAAAAf8AAAAAAAAf8AAAAAAAAf8AAAAAAAAf8AAAAAAAAf8AAAAAAAAf8AAAAAAAAf8AAAAAAAAf8AAAAAAAAf8AAAAAAAAAAAAAAAAAAAAMAAAAAAAAD8AAAAAAAA/8AAAAAAAf/8AAAAAAH//8AAAAAB///8AAAAA////8AAAAP////8AAAD/////8AAB//////8AAf//////8AH///////4A///////+AA///////AAA//////wAAA/////8AAAA////+AAAAA////gAAAAA///4AAAAAA//8AAAAAAA//AAAAAAAA/wAAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/////wAAA//////8AAB//////+AAH///////gAH///////gAP///////wAf///////4Af///////4A////////8A////////8A////////8A//AAAAD/8A/8AAAAA/8A/8AAAAA/8A/8AAAAA/8A/+AAAAB/8A////////8A////////8A////////8Af///////4Af///////4AP///////wAP///////wAH///////gAD///////AAA//////8AAAP/////wAAAAAAAAAAAAAAAAAAAAAAAfwAAAAAAAA/4AAAAAAAA/4AAAAAAAB/wAAAAAAAB/wAAAAAAAD/wAAAAAAAD/gAAAAAAAH///////8AP///////8A////////8A////////8A////////8A////////8A////////8A////////8A////////8A////////8A////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/4AAAP8AA//4AAA/8AB//4AAH/8AH//4AAP/8AP//4AA//8AP//4AB//8Af//4AD//8Af//4AP//8A///4Af//8A///4A///8A///4D///8A//AAH///8A/8AAP///8A/8AA//+/8A/8AD//8/8A/+Af//w/8A//////g/8A/////+A/8A/////8A/8Af////4A/8Af////wA/8AP////AA/8AP///+AA/8AH///8AA/8AD///wAA/8AA///AAA/8AAP/4AAA/8AAAAAAAAAAAAAAAAAAAAAAH4AAf/gAAA/4AAf/8AAD/4AAf//AAH/4AAf//gAP/4AAf//wAP/4AAf//wAf/4AAf//4Af/4AAf//4A//4AAf//8A//4AAf//8A//4AAP//8A//A/8AB/8A/8A/8AA/8A/8B/8AA/8A/8B/8AA/8A/+D//AB/8A////////8A////////8A////////8Af///////4Af///////4Af///////wAP///////gAH//9////gAD//4///+AAB//wf//4AAAP/AH//gAAAAAAAAAAAAAAAAAAAAAAAAAAAH/wAAAAAAB//wAAAAAAP//wAAAAAD///wAAAAA////wAAAAH////wAAAB/////wAAAf/////wAAD//////wAA///////wAA/////h/wAA////wB/wAA///8AB/wAA///AAB/wAA//gAAB/wAA////////8A////////8A////////8A////////8A////////8A////////8A////////8A////////8A////////8A////////8A////////8AAAAAAB/wAAAAAAAB/wAAAAAAAB/wAAAAAAAAAAAAAAAAAAAAAAAAAAAP/4AA////4P/+AA////4P//AA////4P//gA////4P//wA////4P//wA////4P//4A////4P//4A////4P//8A////4P//8A////4P//8A/8H/AAB/8A/8H+AAA/8A/8P+AAA/8A/8P+AAA/8A/8P/gAD/8A/8P/////8A/8P/////8A/8P/////8A/8P/////4A/8H/////4A/8H/////wA/8D/////wA/8B/////gA/8A////+AA/8AP///4AAAAAB///AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////wAAAf/////8AAB///////AAH///////gAP///////wAP///////wAf///////4Af///////4A////////8A////////8A////////8A/+AH/AB/8A/8AP+AA/8A/4Af+AA/8A/8Af+AA/8A/8Af/gH/8A//4f////8A//4f////8A//4f////8Af/4f////4Af/4f////4AP/4P////wAP/4P////gAH/4H////AAD/4D///+AAB/4B///4AAAP4AP//gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/8AAAAAAAA/8AAAAAAAA/8AAAAAB8A/8AAAAB/8A/8AAAAf/8A/8AAAH//8A/8AAA///8A/8AAH///8A/8AA////8A/8AD////8A/8Af////8A/8B/////8A/8P/////8A/8//////8A////////AA///////AAA//////gAAA/////4AAAA/////AAAAA////4AAAAA////AAAAAA///8AAAAAA///gAAAAAA//+AAAAAAA//wAAAAAAA/+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/gD//gAAA//4P//8AAD//8f///AAH//+////gAH///////wAP///////4AP///////8Af///////8Af///////+Af///////+A////////+A//B//AB/+A/+A/+AA/+A/8Af+AA/+A/+Af+AA/+A//A//AB/+A////////+Af///////+Af///////+Af///////8Af///////8AP///////4AH///////4AH//+////wAD//+////AAA//4P//+AAAP/gH//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH//gAfgAAA///8A/8AAB///+A//AAH////A//gAH////g//wAP////g//wAf////w//4Af////w//4A/////w//8A/////w//8A/////w//8A//gP/wA/8A/8AD/wA/8A/8AD/wAf8A/8AD/gA/8A/+AH/AB/8A////////8A////////8A////////8Af///////4Af///////4Af///////wAP///////wAH///////gAD//////+AAA//////4AAAP/////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP+AA/4AAAAP+AA/4AAAAP+AA/4AAAAP+AA/4AAAAP+AA/4AAAAP+AA/4AAAAP+AA/4AAAAP+AA/4AAAAP+AA/4AAAAP+AA/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="), 46, atob("DhgeFB4eHh4eHh4eDw=="), 60 + (scale << 8) + (1 << 16));
};
var img="sJyI/lZWK1ZWVlZWVlZWVlaBVitWVlZWVlaAgXpWVlaAgFZWgHp6VitVVU9WVVV6VlVWVlVVKzErKlZVK4CAVVUxgIBVKytVVTErKytcXDExMTFVMSsrMTErKysrK1ZWVjEGBjFWK1VVKytVXFwxMTFVMVwGVTFdrNetiIiIiIKIs62tra3Xs7PX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fXK1YxK1xWVlZWgICBVlZVVVZWgFZWgIGBVoCAenp6gFZWenp6VlVVVVZWVVZVVYBcVVVVVSsxXCsxMVVVVVaAVTExKzExMSsrMYBWKysGK1YGBisrMTEGBgYGMVwxKysxMTFVMSsxKlVWXDErKytcVTEGBoGI19ess4iIiIiIra2tra2ts9fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19crKysrMVZWVoBWVlZVK1ZWVoB6Vnp6eoBWgHqAVlZWVnp6enpWVlZWVlZ6VlZWgFYqKitWgVYrMYAxVTErVYBVMTExMTErKyoxXCsxVisrMQYrVTErMVYGBjExMSsxMTExMVUxBjFVKjExKwYGKisrVSpVrIiC16yIiIitiIiIiK2tra2z19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX1yoxVjErVlZWK1ZWVoFWgHpWVlZWgHpWeoCAgXpWVlaAelZ6VlZWgFZVVoCAVVaAVisrXFYxgCtWVitWK1WAgVYrKzExMSsrKlZcVVwxKwZWMStVVgBWVQYGVlxVMVVVMSsxMVUxK1ZVVjFWKysrK1ZcVoFcV1fX14Ksra2tra2tra2tra3X19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fXAFxWVStWVlZWVlZWVVZWenpWVVVVVlZWVoB6Vnp6gIB6enp6VlZWVlZWgIBWVVVWKytWKyqBVlUrK1YxVlVcMSpcMTExVisxVlVcViorBgYxACsrBlxVVVVVXFwxVTFVMTFcVlVVXFwxKytVVTExMSpcXAZWgIHXrIitra2tra2traytrbPX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19crVlZWVlYrVVZVVVYrgIB6gHpPgIErVVZWVlZWVlZ6VlZWVlZVVlZWVlZWVlZVKysrKzFWK1aAKyoxMSsxMStVVlYrKysrMSsxMVVVMSoGADFcXFxVVVUrKzExMTFVMSsxKlxVXCtcKyorXFxcKysrACsrACsrK9fXgq2tra2tra2tra2zrdfX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX1ytcMQYrACpcVVVVViuAgYGAgXqlq1ZWelZWVnqBgYBWVk9WVVWAVnpWelZWVoCAKysrMVYxMVUrBlZWBoBWKytWKysxMSsAKisGBisGVVYrKlwxMVVcVSsrMTErMTExKyoxgFVVK4ArAAYrMTErKioGKysrVioqVtesrK2tra2trK2trbOt19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fXKysrK1YrK1UrKysrVYGAVYCBgHpVVVaAgHpWVoCAgFaAVlZ6VlZWVlZWVlVPK4BWKytVMTFVKgCBVisrgFwrVYErVVVVVisrVisrBitWKysxVSsxVVZWVVVVMSoxKytVMTFVK1xVKwYrKisrKysqKyorKlaBMSorrNesra2tra2sra2sra3X19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19cxKlUrKysxK1ZWVlVWgICAVVUrVitVgFZWVXqAenpWVoCAVlZPVlVVVVZWKysqK1YrKysrKysGK4FcMVYrVisxVjErAAAqKytWVlZVVVYrK1YxVVVVMVUxMTErMSsrMTEqAAAqMVYrMTEGKysrBgYqKysrVTFWKysr19eCrbOtra2tra2siLPX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX1wYrVlZWVVZVVVZWVVZWVVUrVVVVVVZWVVZ6enpVVVV6elVVVoF6VlVVVVUrVVUqK1VVKysrKgBWKwArVgYrVQZWVlYrKyoqAFVVVisrVSsxgFxWXCsrKysrKisrKzErBgYrKzExVTExKgArBgYqBgYGKytWKysqKyuA19eIs62tra2tra2IiLPX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fXKlVVVoExK1VVVlZVgVZWVVaAKyQrVit6VlZWelZWVlVVVVVWgFZWVVVWenpVVk9VVVUqKyorAAArK1VVVVUrVVZWVTExKgArgFVVK1VVVVVcK1aBMSsxKysqKysxMSsrBgYrKytWVjErKwYrKyorMQArMVYxKzFWVius16ysra2ts62tra2Is9fX19ez19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19crKytWVlZcVitWVoBWVoGBVVUrKytVVoBWVlZVVlZVK1VWK08rT09PVnpVTytWTytVVVYrKiorK1VWK1UrK1VcVlYrVVVWVYBWVlxWVlZVVitVMSsrKzEqKgYrKysrBgYAKzEGK1xWKwAGAFZWKzFWVoFWMSsGKzErBlbX16yIiK2Ira2trIiz17OIrbPX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX1ysrKysrKysrK1ZWKytWVlZWK1VWVlZWVoBWT09VVXpVVVZPKysrKytWVk8qVU8rJCsrVVZWVVVWVisrVitVVlaAVVVWVoBWgIBVVlZWVVVcVoFVKwYqBgYGKisGBisABitWMQYrgVxWKysrXFwxMVaBVjErKysrMTExKyvX16ysraytrKyIiIiIrYizrbPX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fXMSsrKysrBlZWVVVWK1ZWXFZWgFVPgFVVVlYrT1ZWgFZPVlZVTytVT09PT09VTytPKytWVStWVoArKytWVVZWVoArVSsrgFUrgFUrVSsrVVUxMSsGACsrBgYGKwYGBgYxMTExMQYxXVYxMTFcXCsrMVUxKzExK1YxMVUxK4DX19eCiIiIiIiIiIiIiLOtiK3X19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19dWKysrBisrgVaBgVYrVlxVVoFWK1ZWgFZWTytVT09WVStVVVVPVVVVVVVPVU9VJFVVVStWVVZWVoCAelZWVlZVVTGAKiorVlZWVipVK1VVVSsGMQYGKzErKyorKysqMTErKzErAABWVVUxXFVVKysrKyoGK1UrMTErK1ZcVoDX19eCiIiIiIiIiIiIiK2srK3X19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX1ysrKysrK1aBVYGBXFVVXFVWVlZWVlVVVVVVVU9VVVVPKitVVk8rVVVPVVVWTytPVlZWK1VPVVZPVYBWVlVVVlZWgFZVVVZWVlUrK1VVVVUxKypWKisrKwYGKysGBisxKyoxMSsGADFVVTExBgYAKgYAKwYrMQBWXDExVVUxKoCA19eCiIiIiIiIiIiIra2srbPX19ezs9fX19fX19fX19fX19fX19fX19fX19fX19fXBgAAKysrVlwrVlYrKypWVlVWVlZWVVZVVVUrVVZWelZVVStVVU9WK1VWVVVVT1ZVVVVVTytWT1ZVK1aBgFZWVlaAVVZWKwAAKysrKjFVVSoAVVYqKzEAAAAAKisAKysrKzErKwYAKytVKlaAgIExMStWMSoGMVxWKzFVMSsrKyuB19eCiIiIiIitiIitiK2trbOzs7Oz19fX19fX19fX19fX19fX19fX19fX19fX19crBgAAMYGBVjFWVisrK1ZWVVVWVYBWelZVgFZWVVVWVlUrJCRWVVYrK09VVlZWKytVVVUrK08rgFUrgIGAVVUqT1VWVlZVTytWVSsrMVYrKitVKwYrMVVVVVZVMSsAKysrKyoGBgArMTGA19fX13pVMVYrBjFcMTExXFYxVSsqKiqB19ddgoiIiIiIiIiIra2ts7OzrbPX19fX19fX19fX19fX19fX19fX19fX19fX1wYrKzGBgVxWVisrK1UrgYFWgIFWVlYrVoGBVoFWVlZVKk8rK1VWVlUrVVZWVoBWKysrVlVVVlZWKytWVVZVVlZWVlZWVlVVVVZVVStVVSsrKwYqK1UrVlZWMStWKwArVjErBgArMTEGVtfX1tbWpCtWVisrKysrVlxVMVVWKysrKiur19ddiIiIiIiIiImIiK2tra2ts9fX19fX19fX19fX19fX19fX19fX19fX19fXKwBWgVYrKysrVlaBVlZWVlZVVlZVVlVWgVxVVVVVVisAKytVK1ZVVlYrK1Z6KitVVVVWVoBVVVVWVnp6VnpWVnp6VlVVVlVVVlYrK1YxKysrBiorK1aAKysrKytWgVVWVlYrKzErK1XX1tXV1dXWTzFWVlUrMVUxBgYrVlUxMTFWKySr19ddgoiIiIiIiIiJiIitra2ts7Ozs9fX19fX19fX19fX19fX19fX19fX19cxVlZcKysrBgCBgTExgFZWXCpWVoFcVoFVKytVKysrVisrK1YrK1VVKytWgVZWK1aBgYFWVXpWVoBWVoBWelV6gFZWVVVVVStWVVWAVVUrBisrKzErXDErKysAKoFWK1VVVlYrMSsr1tXPzs7OyNaAKitVKzFVMTEGK1xVMStVVSsAAACs161diYiIiIiIiIiIiIiIra2trbOzs7Ozs9fX19fX19fX19fX19fX19fX11ZWVlZWVlYrBlZWVjErKysrAFVWVlYxVjErKisrKysrKysrKysrKyoqK6uAVXpWVlZWVoGAVlaAVVZWVlZVVYArK1UrKytVK1VVVlZWVSsGAAYrK4BWKysrKytWVlYrVVVWVSorK6vPzsjHx8fHz9dWMTFVVTErKysrKysxMTExBgYrBgCs162CiIiCiIiIiIitiIitrbOtrbOzs7Ozs9fX19fX19fX19fX19fX19fXVoGBMYExKzIrXFyBK1YxKwYrK1ZWMVZWKysrKysrKzErKyorK1YrMVYrgYBVVVZWVVVVVYFWVYBWT1ZWVlZVKysrgCsrK1VWVVVVK1YrAAArKytVVoBWVlZVVlZWVitVK1ZVKyur1p2knZ2dnZ3O1npVgVxVMSsrKjExBiorKiorKysqBirW162CiIKIiIiIia2IiK2tra2trbOzrdfXs9fX19fX19fX19fX19fX19ddXVYyKysxMgBWVlYrVisrK1YrgVYrK1ZVVisxKysrK1YxK1YrVSsrMStVgIBWeoBWVlZWVVZWVYBVVVZWgFZWKytWKysrVVVWK1ZVVVYAKysrVYBWVlZWVlaBVVYqVVVPKysrgdakpJ15eXl5eaTP0CorMQYGKysrVSoqKwYqKisrKysrMSvW162CgoiIiIiIiIiIiLOtra2trbOzs7PX19fX19fX19fX19fX19fX11ZWVlYyKysrKysrBwArK1ZcKzKBVlZWK1ZWKysxMVZWVisrK1ZWK1ZWMVVWVlZVeoCAVlVVVVWl16uBVitWVVZWVVVWVioqVVYrK1ZVgFYrK1VWgFYrVVVVVlWAgCtWJCsrK4HXpKR5eXl5c3N5nc/XgIBVMYBWMTExKzErMSsrKiorKisrMSvX16yCiIiIiIiIiIiIiIitra2trbOzs7PX19fX19fX19fX19fX19fXVlYyMlZWVlZWVlYrK1ZWXFZWVlZWKzJWVjErKzExVisrK1YrMVZcVitWgVxVVlYxKysxVVUrVtbX19fQgYBVTysrgFVVKytWVSorVlZWVlZWVk9VVVVVVVVWK1aAViskKysr1s+knnlPT09PT3N5pM+sVTExXFYrKwYGKysrKysrBgYGBisxKlXX16yCiIiIiIiIiIiIrK2tra2ts7Ozs7Oz19fX19fX19fX19fX19cyMisyVlZWVoGBgVddVlYrK1ZWVlYrVjJWVlYxMTFWMSsGK1YxVlYxK1VcVlYrVVVVVVUrK1aA1s/P1tfX19BPKytVVVVPVYBWVVVVVVZWVVYrVquBgauBgU9WVlaAKytPT4DQnaR5T09PT09Pc3N5yKsABipWKyoqAAYqBlZVVSsABgYGBiorK0/X14iCiIKCiIiIiIitraysra2trbOzrbPX19fX19fX19fX19fX11ZWKytWVjJWXYGBgVdWMisAK1aBXAcrBgAxVjExMVVWVlYxMVZWVgYqK1xWXFZWVSsrVjFWVaXWz87IpM/W19Z6KytVVVVWgIBPVXpWVlVVK4GsgE8qVVZWK09VT1ZPT1WA1qSeeU9PTk9PT09Pc3Ok0CorVjErACsGBjExKysrAAAAKysrKwYAKlXX14KCiIKIgoKIrYitra2tra2tra2zs9fX17Oz19fX19fX19fXVlZWMlZWVlZWVlZdgVZWVitWVjIxMTIHAFYrKysrKytWK1ZWVoErMYFWVlZVMSsrKytVKysqq9bPo52dnaPI1telT1ZWVVaBgFZVVlZVVVWBpStPgaysgYGBq4FVVlVVVYDQnnlPT05PT09PT09Pc57WTzErBgYGBisrVlYGKysGKysrVlwrACsrAFXX14GCiIKIiIiIiIiIrK2tra2tra2ts7PX19ez19fX19fX19eBgVZWVlZWLFZWVlZWV11dXYFWKysrVisrKysyKysrK1xWK1ZWVgArVlaBVlYrKitVVSsrKyvWz895eXl5eZ3I1telT08rVlZWgCtWVlVWVqwrq9arpVZWVk96gYGAT09P1qR5eU9OTk9PT09PT09PedarKwAGKwYGKytWgSsAACtWKwAAKwYGKysrAFbX14GCiIiIiIiIiIiIrKytra2trbOzs7PX19fX19fX19fX112BgVaBVissMjIyMjJWVoGsglYrKytWVlZdgVaBgYGBKytWVjErKzFWVlZWVitWVlZWKwZVgNakpHp5eXN5eaSkz9d6ek9WK1WBT1ZWVlaBgYGrgYFWKysrK09PeoFWT6zWeXlPTk5PT09OTk5PT09zpNdPAAYrBgArMSsxKysrKysrACsrACsrKysrKoHX14GCiIiIiIitiIiIrK2tra2trbOzs9fX19fX19fX19fXgYGBViwrB1ZXVlZWViwsgYFdXYGBVlYyK4EyVoGBrFYGMlYrAAdWgVwrK1ZWVlZVVlaAMYGlz515pE9zc3lzeXmdz9bWek9PVoFWVlYrVqys19CsVisrKyskVnpWVVZ616R5c05ITk9PT0hOTk9PT3Od1oAqKysrAAArMQYAKysrKysrVisAKzEqKysqKqzX14GCgoiIiIiIiIiIraytra2trbOzs7PX19fX19fX19ddgYFdXYFXVldWViwsLCxWVlZdXV1dXYFWXSuBgYFWK1ZWKysrVoGBKysxVlZWVitWVoCBVnrPeXOkT05PT05Pc3mk1tarpVZWgVZWVoHX1tfXgYGBgHqAgIBWTypVK0/WenlPT09PT09OSE9PT09PT3nP0CorMSsGBysrAAAGBgAAK1UxACsAKysGKysrK9bXrIKCgoiIiIiIiKytra2tra2ts7PX19ez19fX19fX14GBgYKCgoFWKysrK1ZWLCxWMlZWVlddgYGBV1ZWVisHKytWVlxWVlwrVlZWVlaBKysrVlxWq6t5T3l5TnNOTk5PeXnIyNelgIGBgYGBrNfX16xWK1ZWgIGBrKxWK1ZWetB5T3lPT05OT0hIT09PT05OeaTWTwArKzErBgYGBisrKysrKysABisrVisxMSsrT9fXgoKCgoiIiIiIiIisraytra2trbOzs7PX19fX19fXgYFdgYGBgoFdV1dXVlZWLDJWVlZWVleBgYGBXV1dgV0rK1aBVlZWK1ZWgYFWK1YxKytVVivQpXlOTnpOc05OTk5PeZ2dz9Z5gICBgNbX1oHXgYGBq6yrrKysgVZWeiuBz3l6c0hOSE5PTk9PT09PT055nc+lACsrKysrBgArKysrVisAKwArKwCBVisrK1VPVtfX14GCgoKIiIisrKysra2tra2tra2zs7PX19fX19eBgoGIiIGCgYGBgVdXV1ZWVlZWVlZWVlZXgYGBgYGBgYGBVlZcVlYrVlZWVlYrKytWVlYxK9CkeU5OeU9zT09PTk5PeXmd1c96gYHQpdesrNfX19fQrIHX19fXrKWBVtakenokSE5OT09zc09PT09OTnN5yM8qKwYGKysABisrKysrKwYrKyorAFZWKysqVisqgdfX14GCiIiIiIitrK2trK2tra2trbOzs9fX19fX14KBgV1dV4GBV1dXgVddV1ZWMlYyMlZWVlZWXYGBgYFXV4KBVlZWVlZWVlZVMVYxgVZWKwBP1npzTk55eU9PT05OTk5zc3nI1oGBq6us19fX19d6gYGBelVV0NalgXqB16WlJEhOT05PT3NPT09PTkhPc3mkzysrKysAKysrKysrAAAqBitWVSsrKlZWAAYrACokrKzXrIKIiIiIiIitra2srK2trbOzs62zs9fX19fXgoGBgYFdgVdWgYGBV1ddgV1XVzIsVlZWVjJWV11dgV1dgTIrVlYAKzFWMSsxK1ZWVlZWK1bWeU9OTk96T09PT05OTk5OeaTP1qXX19fX19es13qBpXpWgYGsgax6VoDW0FUkT09PT09Pc3NPT04kTk5zeZ3QKysrKysAAAArVlYrACoAK1UrAFYrgFYrKwAAKyQrK9fXgoiIiIiIiIitrIiIra2tra2trbOzs9fX19eBgYKCgYFXXYKCgoGBgYGCgYGBV1ZWVlZWVlZWVlZXgYFXV4FWVisAAAArKysrVlaBgVYrVtB5Tk5OT3pPT09OTk9OTk5znc/X19fX19fX19fQrNCBgdCrq4GrgIGBpdfPek9OTnNzT09Pc09PSEhOT3N5nc9WKysrVisqAFZVVSsAJCorK3pWVit6VitPKytWKysrVtfXgoiIiIiIiIisrKysrK2tra2zra2zs7Oz14KCiIKIgoKCgqysgYGBgYKBXVdXV1ZWVlZWVlYyMlZWXV1dV11dXV1WVlYrVoFWMoGBVlar0HNOTk5Oek9PT09OTk5OTk55yNbX19fX19fX19fXrNfXpYCArNelq4HX16V5JCRzc09PT05zTk5OJCRPT3md1tcrACsrKlYrVgAAACtPKysrVU9WK1ZWVlaBVlVWVlYqpdesgoiIiIiIrIisra2tra2tra2trbOzs7PXiIKsiIGBgYGBgoKBgYGBgYFdXYGBgV1WMjJWVlZWMjJWV12BgYGBV12BVitWVlZWXFwrVtbIc05OTk55Tk9PT09PTk5OTnOk1tfX19fX19fX19fX19CAq6vX19es0NelpXlOeXpPT05ITnNPT0gkJE9PeZ3Q11UrKwAAK4BPKysrVoCAVlZWVnpVVlaAVVZPVYCAgCsr19eBgoiIiK2siK2sra2tra2trbOzs7Ozs7OBgYGBgYGBgV2IiIiBgYGBgYGCiIiCgYFXVjJWVlZWMlZWVoGBgV2BXVZWVlYrVjFWVitW1qRzTk5OTnlPT09PTk9PTk5ITqTW19fX19fX19fX19fX16zW1tfX19fX16SkeZ6kT09PTk9zc09PSCQkTk+dndDQT1VWVisqT1ZVVYBWVVZ6VlVWgHpWVYBVVlZVVVZWVipW17OCrIitrKysraysraytrbOzs7OzrbOzs4GBgYKIgoKBgV1dgYGBgV2BgYFXV1eBgYGBVlZWVlZWLDJWVlaBgYFXVleBVlZWK1ZWVoHWpHNOTkhIek9PT09PT09OTk5PpNDW19fX19fX19fX19fX19fX19fX19fWpXqlq09OT09Pc3NPTk5IJCRPT3l51tdVK4CAVSpPgFVVgFZWVVZVVVaAgIBVgFZWVVZWVVVVVU+s14iIiK2sraytrKysrKysrbOts62ts7OzgoKBgYKIXV1dXV1dXV2BXVeBgV2BgV1dgYGBgVZWVlYsMlZWVlZWgVZWV4GBgYFWKytWpc+dc05OTkh6c09PT09PT09PT0+kz9bX19fX19fX19fX19fX19fX19fX19ekpdZ6T09PT095c3NOTk5ITk5Pc53X14BWgIBVVVaAgIBWVlZWVVVWgHpVVlV6VlVWVlVVVVaAVVbX14GtraytrKysrIisrKysraytra2zs7NXgYKBgYKBgV1dXV1dXV1dgV1dXYGBgVdXgYGBgYGBVlZWVlZWV4FXgaysrFZWVlZWViusz3lzTkhIJHpzT09PT09Pc3NOT8/W19fW1tDW19fX0NfX19fX19fX19fX16XWpHlPT09PeXlzc05OTk4kJE9zpNfXrFVWelVWVnqAgIGAVVZVVYCAK09VVVVVVVVPK09PgFZWK6XXiK2zra2srKysrKysrK2srK2trbOzs4iBgoGCgoGCgoKCgYFdV12BgV1dgYFXV11dgYFdXV1WVlZWLCwsVlaBgqzX19esVoGBetCkeXNOSEgkeXNzc3NPT3Nzc0+k0M/Jz9fX19fX19bX19fX19fX19fX19fQ1s96ek9OT3N6eXpPTk5OTyROc3nIz9fXT4B6gFZVVlZWVlVVVlVVVlVVVVVVVlYxVSsrVVWAVYArK9fXga2trKysrIisraysrKysrayts7OzrYisiIFdiIKCgYGCgoFdV1ddXV2BgYGBgV2BV1ZWV4GBgVdWLFZWLFYsVnqB1tfXgYGl0KSdc05ITkh6eXNzc3Nzc3l5pc+kpKTW19fX1tDW19fX19fX19fX19fX19fQpKR6T095enpzeUhOTk9PT095pKTIz9dWVVZ6VlZVVVVVKypVK1ZWVVUrK1VVKytVKytVVVZWVlUqgdeIiKysrKysrKysrKysrIisrK2tra2sgoGCgoGIgYKBgYKBV1eBXVddXV2BgYGBV1ddV1dXgYGBgVdWVlZWVlZWKyxWrNfX19CrpJ55Tk9PSHp6c3Nzc3OeycmlenqkpdDWz9DW19bX19fX19fX19fX19fX18+lpIB6enqkc3NzSE9PTyQkT3mdeZ3P16zQrKyBq6ylpYGAVlUAgFZWVSpVVStVVVUrVVZWVSsrMStP19eCrKysiIisrK2srK2srYisraysrIGzgoGCgYGBgYGBgYFdgYGBXV1dgYGBV4GBgV2BgYGBgYFdgVZXVlZWVixWVisrgdfX19CknnlOTiRInnlzc3N5pKV6enl5pKWlz6vQ1tbQ19fX19fX19fX19fX19fX16WkpICApHpzc09PT09PKk9Pc56kpM/XrIFWVU8rKysrKyoqKlWAKitVK1WAVlUrVXqAVlZVK1VVVVWB14KsrKysrIiIiKysiNfXs4isrK2tK4KsgoKBXYGBgYFdgYKBgYiCgVaCrIKCgVddV1dXV12BgYGBgYGBgVZWVlZWVlArenp60KWkeU9IT0ikenNznqWlenl5eaSlpaur1tfQ0NfX19fX19fX19fX19fX19fXrIClpYGlenp6paysrIBWeU9zeXmd0NerpXpPTyoqVVUrKioqVVUrVStVVoBWgFZWVlZWVlVWKytVVlXX14KsrIiIrayIrKyI19fXiKytrawlVqyBiKyBgoiCgoFdgVeBgYFdgV2BgYGBgYGBgYFdV12BgYGBgYGBXVZWVlZWVlBWVlal0KV6T0hPT6R5c3rJpHp6eXl6paWl0NbX0KvX19fX19fX19fX19fX19fX19fQgdClq6WlpaVVT09PJE9PT3N5nqXX19fX19fQVStPT1VVVisrVVZVeoBVVlVVVisrKyoqK1VVVVVVK4HXgoiIiIjXs6ysrIiIs6yIrKysrAErgqyBgqxdgYKCgleBgYGBgYGBXVdXV4GBV4GBgYGBgYGBgoFXgYFXXVZWVlZWUFBQVoHWpaRPJE9PpHp6paV6eXp6eqSlpaXW19ar19fX19fX19fX19fX19fX19bX19fQeqvQ0KV6eiRPT09PT09PeXl5o8/X19fX19fX14GBKytVK1WAVVVVVlZWVlVVVVVWKytVK1VVVSsqK9fXgoiIiKytrKysrIisrKysrKysKwEyrYhdgl2BgYGBgoiBgoGCgoiCiIGBgYiBgoGBgYGBiIFXXVdWXYGBgYFXV1dWUFBQgdelpXpOT3OkeqWlenl6enp6paWl0NbWrNDX19fX19fX19fX19fX19fX1tfW19Cs0KWlpaWlT3lPT09PT09PeZ7P19fX19fXq4Gr0NCAKitVgFZVVVVVVitVVVaBgTFVVVZVVlVVVVUrrNeCrIiIiIisrKyIrKysrKysra0rKyuBrKyCgoiIiIiCgoKsrIKBgoKCgYGBgoGsgYFdgVddgV2BXYGBgYFdV1dXgYFWVlCB16SlenlzeqSlpaR5eXqAenqrpdDQ16ys1tfX19fW19fX19fX19bX1tfW0NbX16yreoCrpaV6eU9PT09PT095pM/W19fX19bX1oArK4CrVStVVlVVVVZVVVZVgFZWK1VVVlUrVVVWVVZW16yIrIiIrK2IiIiIrKysrK2srCsrASytgqyIgYKCiIGBgYKCgYGCgYGBiIiBgYKBgYGBgoGBXYGBgYFXV4GBgYGBgYGBVoHXeaWkenp6paWkek95eqWAgKusrKzW1tbX19fX19bX19fX1tfX1tbQ19bQ19DX0KulVqulpXp6T09PT09PeaTIz9fX19fW0KXQ1k9PK4DQVlZVVVUrKyorVlUrVVUrVVUrVVVVVVZVVSvX14KsiIiIiIiIiKyIiKysrKysKysBAYGsgYGBgoKCgYGBgYGBgYGBgYGBXYGBgYGBgV1XgYFdgYGBgYGBV1eBgVeBVlZW19d5paWkpKSlpXp6eXqlgKWlrNCl0NDQ19fX19fX19bW1tbW19fW1tDW0NbXq9fQq9B6gKWlpXp5eU9PT095pM/W19fWrNbQq3rWpaVVeqWBK1VWKyoqKysrKysrACtWVipWK1ZWVVUrKoHXrIiIiIisrKysrKysiKysrKwlJSsAK6yIgoGCgoGCgoGBgYGCgoGCgYKBgYFdgYFdgYGBgYFdgYGBgYGBgYGBV4GBgVas14CkpaSlpaWkenp5eqWApaXQrKvQ1qzX19fW1tfW1tbW1tbX19bP0NbQ0Nal19bQq6V6paWrgHp6VU95eXrP1tfX16x6gNDPgIDW1np6K1VVVSsqK1UrKysrKyoqVYCAVYBWVVVVVVUqVdezgoiIiIiIiKyIra2srKysrAErKwEAgayCgoGBrIGBgYGBgYGCgYGBgoKBgYGBgYGBgYGBgYFdgYGBgayBgYGCgoGBgdDXq3qkpKulpXp6enqlgKWrq9alrKzQ0NfX19DW1tDW1tbW1tbW1s/W0KvQ1qzX19DQpYClq6ulgIBVT1V5pNbX19fX19elgNbQT4CAgFUqK1ZWVitWAAArKipVVStWgICAVVZVVSQrVVUr0NeCiIiIiIiIrKyIrKysrKysASsrKwAsrYiCgoKIgYGCgYKCgYKBgoKBgoGBgYGBgYGBgYGCgYKBgYiIgYGBgayBrKyrrNfXpKSlq6ulenp6gKWlpdDQ0KXQrNbX19fQ0NbQ0NDQ0NbW1tbQ0NCrq9as0NfW0NCrpaWlpaulpXp5VaTW1tfX19DW16uBpaulT0+lKypPVoBVK1VVVVZVVlZVK1VWVlVVVSsrKiorVVWA16yIiIiCiIisiIiIrKysrKwBKysrAQCBrIGCgoKBrKyCiIiCgaxdgYiBgoGIgoKsgoKBiF1XgoiBrNfXrKyBrNesrKzX19ales/PpaV6enqlpaWl0NCsq6zQ19fX1tDQ0NDQq9DQ0NbQ0KvQq6XP16vQ0NDWq6urq6Wlq6WlgHp6z9bW1tfX14GB1tB6etZWVoErKlVWKwArKysrT1VWK1ZWK1VVVVUqKysrKytVVVXX14iIgoKsrKysrIiIrKysiAEBKysrACysgYiIgoKCgoGBgoGCrYiCrIiIrIKIiFeCgoKIV11XgYGIgays19fX19fX19fX18+l0NClpHp6eqWBq6XQ0KulrKzQ19esrKvQz6ul0NCs0NDQq6ulpdDQq9DQ0Narq6urpaWrq6uApKWl1tbW1tbX19aBgYB50KWlVXorT1YrVVUrAAAAKytWVitVVVVVVSsrKytVVisqK6zXgYiCiIiIiKysiIisrIiIAAErKysBAYKsiIiIgoKCgoiIgoiIgoiCXYGIgoKCXV2IgYGBrIGBgYFdgayBrNfX19fX19fX1qXQ0KV6enp6pYCrpdDQrKXQrNDX0Kysq6urpaXQrKzQq6ulpYCl0Kys0Kys1qvQq6ulpayrq4CkpKXP1tbX0NfQpYGAT0+l0NBPgStVVlZVKyoqKlaAVlUAAIB6eitVVgArKytVK1VWgNeCrIisiIiIiIiIiIiIiIgAASsrJQEAVqyIiIKCXayCgoFWgVdWgV2BgoKIiIiCrIiIgoiCV4GBiIGBgoGBrNfX19fX19fWq9ClpXp6enqlgKur0NCsq6ys0NfQrKurpaWlpdCsrKylpaWAgKysrKzQq9DW0NbQrKulrKyspKR6pM/W19fW0Kus0NfXrIDW1lWAK1WAMVZVKysrKysqKitWgVVVK1WAVlZVKzFWgFVW162CiIiIiIiIiIiIiIiIiAAAASsBAAArgoGBgYGBgYKBgoKsgYGBgoiIgoGBgYGIrIiCiIGBrKxdgYGBgYGBrNfX19fX19DP0KWlenp6eqWBq6zQ0KysrKys0Kysq6ulpaWlq6urq6WlpHqlrKysrIFWViwsLFZ6pavQrKylpJ6kz9bX19bQ19fX19fX19fXgSsrK1ZVVSsrKysrKytWK1YxKysrVStWVSsrVTErVlWs14KsiIiIiIiIiIiIiIiIAQEBKwEAACuIgoKCiIKBiIKCrKysgoGBgoKsgoKCrIiIgoGsgYGBgldXXYGBgYGB19fX19fW0M+rpaV6enp6paWrrNDQrKysrKysrKWlpaWlpaWlq6WlpKR6eqWsgVYrBwcBAQEBAQErLKXQ0KWlpKTP1tbX0NfX19fX19fX19fXgFZVK1UrKlUxKysAKzFVVlZWVlUrVVyAgIBcKlZcVYDXiKysiIiIgoKIiIiIiIgBAQErAQAAK6yCgqyIgoKsiIGIiIKIrIGCgYKBgoKBgYGIgYKBrIJXgYGBgqzX14HQ0NfX19bQ0KulpXp6VoClpaysrKysq6ysrKylgaWlpaWlpaWrpaWAgHp6rFYrBysrB1aBgYFdVisBK6ys0KvPz8/W19fX19fX163X16zQ0KxWgFUrKiorVSorKwAAK1YAVVZWVitVVVZWgVUxVlYrVdeIgoKCgoiIiIiCiIiIiAElKysBAAArrIiIiIiCgoGBgYGBgqyCiIGBgYGBgYGBgYisgoGsrKysrIGs19fX19fX19fX1tDQq6WBenp6gaysrIFWVlZQVleBgYGBgICApaWlpauBgHp6T3osBywsLCwsMiwsLCxXMgErV1fQ0KvPz9DX19fWrNfX19etVoGBrCQrVSsqADErKysAKysAKitWMTFWVisrKoArBlUrKytV1teBrIiIiIiIgoiIiIiIASsrKwEAACysiIisrIKCgleCgl2BrIGCiIGBgYGBgYGCgYKBgqysgoGs19fX19fX19fX19fQq9DPpIF6enqlgSsrASsrKywrKysrLFZ6enqAgKWlpYB6VlZPLCssLCwsLCwHBwcHBwEHAQErK4HQpc/V1dfX19dQVlet14FQrKyBKisxKyorKysrACtVKwAqgFVVVVZVVVyAKytWgVZVVoCr14KsiIiIiIiCiIiCiIgBKyslAQAAVqyCgoiIrKysrKyIiIGsgoGCgoiCgYGCgoKsrdfX19fX0dDX19fX19fX19fX19fQ0NClpXp6e1ArVl0sLCwsLCwsLCwsKyxWVoCBpaWlgHpPTyssLCwsLCwsLCwsLCwsLCwsAQEBLIHPyM7Pz9fX13osCCxdVlbX16xWKysABlwxVSsrVlZWVlxcK1ZWVVZVVlVWVoCBVTFcVVbXgYKCgoKIiIKIgoiCrCUrKyUBAABWrYiIiIisgoisgoKCgYGtrays16ytrdfX16ysrNfX19fX19fX19fX19fX16yl0NDQ1qWBpYEBK1YyLCwsLCwsLCwsLCwsLCxWeoGBpYF6VisrLCwsLCwsLCwsLCwsLCwsLCwsAQErVqXPzs/P19bXrCssLCwBK4GBgayBMStWXCoxKysrVipVXCorXFxWVlVWKzFVVVYrVoAqK9esXYiIiIKCiIiIgoiIJSsrAQEBAIGsiIiIiIiIgYKtrKytrIKziKysgqysrIGsrNfX19fX19fX19fX19fX19fX19CrpdDWrKWsKwEsLCwsKywsLCwsLCwsLCwsLCxWVlaBVisrLCwsLCwsLCwsLCwsLCwsLCwsLCwrKwEses/Iz87W1tbXTyUrLFZWVlYAK6xWKysrBgYqBitWVVYrK1YxMQAqKytWXFUxVitWKwZW16xXgoKCgYiIgoKCgoIlKyslAQAAgayIiIKCgYiCgoGsraysrNesrIKC19fX19fQ19fX19fX19fX19fX19fX19fX19fX0KyrrIErASwsLAEBLCwsLCwsLCwsLCwsLCwsAAEBAQEsLCwsLCwsLCwsLCwsLCwsLCwsLCwsACsrpMjPz9bW0NeBVlZWLCsrKyoAK1YAKytWKgAAAFaBVisqVSsrKlZVKlVcgVYrK1UAMVaH11eCgoGBgoKCiIiCgisrKyUBAQCBrIiIiIiCrIKCgtfX19esrILX19fX19fXrNfX19fX19fX19fX19fX19fX19fX19fXrNCsKwEsLCwsAAErKywsLCwsLCwsLCwsLCwBAQABKzIyLCwsLCwsLCwsLCwsLCwsLCwrKysrUFZWec/V1tfX19ArKywBASsrKwArKwArKlYAKwYAXFwrMVZWMTFcVlYGACsrKysxK1UxK1bXXYGBXYGCgoKCgoKCASsrKwEBAYisra2srIGBgoKsrNfX16zXrNfX19fX19fX19fX19fX19fX19fX19fX19fX19fX19esrIEBASwsLCsAKwEBLCwsLCwsLCwsLCwsLCsAAAArLCwsMiwsLCwsLCwsLCwsLFBWVlasrKyr0Kx6z9bP19DW1lYrVlYsLCxWVoFWKytWVgYrKlZWKwBWVlYrK1YxVisAKwYAK1ZWKysqK9ddXV1dgYGBgoKCgoEBKyUrAQEArKyBgVesiIKBrYHX19es19fX19fX19fX19fX19fX19fX19fQ19fX19fX19fX19fX19fXLAEsLCwsASsrAQEsLCwsLCwsLCwsLCwrKwABAAAsLCsHKywsLCwsLFZWVnuBgaysrNfX19fX19DQ0M/X0M+reitWrNfX19fXrayIgVYrKytWVjFVMVYrKysrK1ZWMVYAACsrMVxWKysrrFddXYGBgYGBgYGCgQEBKyUBAQGsrIGBgayBrIGsgdfX19es19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX14ErASwsLCwsLCsrK1YyLCwsLCwsLCwsKwBWASslACsrKwABLCwsLFZWVlZQVlAAACQrVlZ6gavW19fX19fX19fX19fX16ysgV1XV1ZXgYErMVVWVisrXCsxKysxVitWVlZWKysxXCorMSuBgV1dXV1dXV1dXYFdXgEBKwEBK6ysrKysgYGBV6yB19es19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19elVisrLCssVlYsAFZWgYGBgVdWLCwsLCwrAFZWLCsAJSUrKwErKyxWVlZWVlZWKysrKyslJSsrgXp5pM/P0Nar19fX16yBe3tXViwrKyssgVYqK4AxK1ZWK1ZWVlYrK1ZVgCsrKzErAAArVYGBV1dXV1ddXVddXVeJVwEsKwErrIGBgVeBgoKs19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX1tfXVitQLCsrKywrJSUAAAArUHqBgVZWLCwsKysrK1YrKwAAACsrACtQe3p6VlZQUCsrK09QUFZWViuBVnrPz8/P1tfX19esgoJXVywrAQABAQEBVitVVlVVVlUrVlZWgSpVVlZWK1aAKisxAFWBgFdWVldXV1dXV1dXXViJVwcsAVfX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX16wAJFArKysrKyUAAAAAAAArK1ZWVldWVlYrACsrVlYrAAAAK1ArVoFWgSsrKysrKwAAAAAlKysrgdfWpc/Iz8/X19fXrYKBVisrAQAAASsrKwEAVlZVVSsrKyuAgYExVYFVgFZVVlaAVlUrVlZWVlZWVldWV1dXV1dXV1iDMywrrNfX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fQrNDX19fX19fX1yQrVisrK1ZPKwAAJSsrgazW0HpWVlZWViskVitWVk8AAAAAK1aBVlYrKysrKysrKyskAAAAAABPVaTW19fX19fX19esV1YrAAAAASsrKywsLCtWVVUrBisAK1YrKypWVisrVSsrKnqAVnqAVlaBVlYyVlZWV1dXV1dXV1hYLCuB19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fXKyuBKysAKyUrKyQlVlbQ19aAT1ZWVk9PKwBWK1ZWViUAACsrVlZWT096gHpWTytWVoGBq6ysgXp6pMjIz9bX19fX14FWVisAACsrMlZWVlZdVjExVisGBitWACsrVlYxBitWMSsrVXp6VlZWVlYyMjIyVlZWVldWVlhXV1gBACssgays19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19d6AIErKyskK1ZWq9fX19fX1qWAgHp6Vk9PT1ZWVlZWTysrK096VnpWgXorJAAlKysrACR61tbX19DX1s/Pz9fX19fXgVYrK1ZWVlZWVoGBgTErK1ZcVisAKisAKytWMSsrVitWKytWelVWVitWMiwsLCwyLDIyMjIyWFgzWFYAKywrKyssgdfX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX16UApYAkK08lJHrX19DQgHpVVVZ6gYB6VlZWVlZWVlZWVlZPVlZ6VnpWT1ZWVk8rKwAAJCtPT3rP1tfX18/Q19bX0KsAAAArVlYrKysrKysrBjFWVjErVisAKysrK4ArKzErAAAAVVZWVVZVK1ZWKyssLCwsLCwsLCxYWFgzgQArKysrKwEAKyyB19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX1ySl0CQrKyRV1tCrpaWBgIB6T09WenpWVlZWVU9WVlZWVlZWVlZPKyQrK1ZWVk8AJCtPT3p6eqTP0NDP0NDW0NfXrAArK6xWVisrVlYrKysAK1YxK1ZWKytWKwAAVisrK1ZWAFYrVitVVVUqK1csLCwsLCwsLCwsLFhYMy2BKysrKysrAQAAAAAlKysrKysrKysrKyssLCxWVlZWVlZWgYF6rNfX19fX19fX19fX19fXpKSleiQrgdbWgFUrK09Wenp6elZWVlZWVlZPT09PT1ZWVU9WelZWVlVPKysqVlZPT1Z6gICkpdfX19DW1tbW0NfQKyuBrCsrVlZWVlYrMSsrVSsrVisrVlYqAAAAKysrVisAKytWVlZVK1ZWViwsLCwsLCwsLCwsNFgzLVdWKysrAQEBAAAAKysAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABW19fX19fX19fX19fX19bXz3l6etDWqysAT3p6enp6enp6elZVVVVVT08rT09PT09PVnp6enqBpYF6elYrT3p6enqkpKSl0NbX1tDW1tbW1tdPVtAyKytWVlZWMSsxK1ZcKwArACsrKysAAABWVlYrAAAAK4FWVVZWKytWKyssLCwsLCwsLCwzNDMtV1crKwEAAAAAAAArKwAAAAAAAAAAAAAAAAAAAQAAAQEBAAAAAIHX19fX19fX19fX19fX19fQeoDX16UkAE+lgIClpaWAgHqAgHp6T09PK09WKytPT3pWVlV6eoClpaV6enpWT3qAenp6paXP1tfXz8/W19fQ13qsgStWVlZWVisrMlZWXFYrBgAAKwArVisrVVYxgSsrVlZWK1ZWVVasiFcsLAcsLCwsLCwsLDMzMzMtVywrAAAAAAAAACslACUBAAEBASUlJQEBAQAAACUlASUlJQAkrNfX19fX19fX19fX1tbW1s+l19erT096q6vQ0NClgHp6VVVVelVPT09PVk9PVlZWelZVVVVVeoClpaV6eqWAeYClpKSkpdDX19fX1tbW1tbXrKwrVlZWVlYrXYFWMjErKysrAAArAFZWVlYrK1YrVlYrKwYrVVZWrNfX19fXiDIHCCwsLCwsWFg0My1XLCUAAAAAAAABKwAAAAAAAAABAAABAQAAAAABAAAAAQEkAFbX19fX19fX19fX19fX1tbQz9fXq3pPetDQ0KurgHp6enl5VVVVT09PT09PKytPKysrT09VT09PeYCApaWApaWlpaSrq6Wl0NbX1tbW1tbW1tbXgVZWXFxWVlZdVisrKytWVisrKwAAVlYrKwArACtWKzJWK1VVK60z19fX19fX19eBLCwsLCxYNDMtLVcsAQEAAAAAAAErAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAApdfX19fX19fX19fX1tbW1tDX19CAenrW19Clenp5eXl5eXlVVU9PT08rKysrVlZPTysrT1VVT09PeoB6paWlpaSrz6Wlz9bP19fX19bPz9bW1td6gVZcXCsyVlZWVjJWVjIrKwAAKysrVgAAACtWKytWKysrVlasXgmt19fX19fX19fXrFYsLDQ0MzMtMzIBAQAAAAAAASsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACTQ19fX19fX19fX19fW1tbW1tfWq4B60NfQpHp5eXl5eXl5eVVPT08rKysrKysrK1ZWVisqT1VVVU5OeoCkpaWlpaXPz8/P1tbW1tfWz8/P19fW11ZVVoGBVitWVlZWgV1WVlYrK1YrKysrAAAAVlxWMgAAK1Yrgtc0CVjX19fX19fX19fX19dXMzMzMy0tVwEBAAAAAAArKwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKtDX19fX19fX19fW1tbW1tbW19ereqXX1qWlenl5eXlVVVV5eVVPJCsrKyUlJQEAAAArTyRPT09PT05PeoCkpKSlz6ulpc/P1tbW19fQz8/X18/XgFYyVlZWKyxWVlZWVoGCXVYrAQArVlYAACtWMoErACsrKzLXrS0JCQk0iYnX19fX19fX19czMzQzMy0tKwEAAAAAACsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABP19fX19fX19fW1s/Pz9bX19fXq4CA19elq6V5enp6enlVVVVVTysqKyQAACUrJQAAAAAlJE9PT09PT05PeoCApKSlz8/Pz9bX1tfW19fPz9bXz9erT1ZWVjIyMixWMlZdVoFXXSxdgVZWVlZWKytcgVZWK1YyrdeDCQkJCQkJCQk0idfX19fX1zMzMzMzLSwrAQAAAAAAKwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHrX19fX19fX19DQz8/W19fW1qWr0NbX0KXQgIB6enp5eXl5VU9PKyokAAAAACUAAAAAAAAlT09PT09PT055enqkpKSrz8/Pz9bX1tbX18/P1tfP1tBWK1ZWKyxWMjIrVoFWgV1WgayBV4GBVlZWVoGHVoFWK13X114JCgkKCgkJCgkJLV6z19fXMzMzMzMtLSwBAAAAAAErAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkpdfX19fX19fXz8/P1tfW0NDX1tfX19al0KWkpKSkenl5eXlVVU9PJAAAAAAAAAAAAAAAKytPT09PT09VT1V5eaSlpaTPz8/P1tbW19fX19bW1tbX0KWAVlZWK1YyMixWVlaBVlaBgVaBgVaBgYFdK1xVgStW19ezNAkKCgoKCgoKCgoKCQkzidczMzMzMy0tLAAAAAAAACsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACTW19fX19fX19fQ0NbX1tbX19DW19bXz6vQpaWkenp5eXlVT09VT08rAAAAAAAAACsAACsrT09PT09PT09PT09PeqWlpaWlz8/P1tbW19fX1tbW1tfQgIFWVlZWVisyVjJWVlZWVlZWXVZWVl1dVitWVlZWK4jXs60uCgoKCgoKCgoKCgoKCgkJLTMzMzMzLSwsAQAAAAAAKwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAK9fX19fX19fX19DQ19fW19fW1tal1tar0KulpHp5eXl5eXlPT09PKyslJSUBAAAAJSsrJStPTytPT09PT09PT095pKWkpaXJz8/P1tbW1tbW1s/W19BVgYGBVlYrKywyKywyVlZWVlZXVlZWgYGBgYFWKytX19ezgwoJCgoKCgoKCgoKCgoKCgoKMzMzMzMtLFYBAAAAACslAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABW19fX19fX0NbQ19fX19bW1tfQpavX0KvPpaR6eXl5eXl5T095TyoqKysAAAAAAAAAAAAkKysrT09PKyQkKitPT3l6paSkpMnP1s/P1tbW1tbP1tfX16ysrKysgVZWVlZWLCxWVlYyVlZWV4GBgYGBgStWK4LXrbNfCQkKCgoKCgoKCgoKCgoKCgozMzMzMy0sLCsAAAAAKwEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHrX19fX1qvP1tfX19bWz6XW0KWr1tfQq6ukenp5eXl5eU9PeU8kKysrKyQAAAAAAAAAACsrKisrKyskKiQkKk9PT3mkpJ6epM/Wz8/W1tbWz8/P1tbWelaBgVdWVldXVlYyLCwyVlYyMlZWVldXrIGBgYEs19etrV4JCgoKCgoKCgoKCgoKCgoKCjMzMzMzMywsKwAAAAArAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgdfX19akpdfX19bW1qulz9alq9DW1s+lpYB6eXl5eXlPT09PJE8rKysrKyskAAAAJCsrJSQkJCskJCQkJCQqKk5Pc3mkpKSkpM/Pz8/W1tbWz8/W1tZ6eoGBVlaBgYKBVissVlYyMjJWLCwrgYGsrFaBV4HXs7OJNAoKCgoKCgoKCgoKCgoKCgoKMzMzMzMtLSwsAAAAACsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACs19fWpYDX19fQ0NDQq8/Pz8/Q0NbQq6Skenl5eU9PT09PKiQqKysrKiQkKyQrJSQkJCQAJCQkJCQAAAAAJCQkTk9PT3qennmkyM/Pz8/W1tfWz9XW1lZWgYFXgYFXXYGCgVYyLCwsK1ZWVldWVoFWVldXs9etrYM0CQoKCgoKCgoKCgoKCgoKCgotMzMzMy0sLFYAAAABJQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJNDX1qWk1tfX1s/W1tCr0M/W0NDQ1tClpIB6eXlPT09PJCQAJCQrKiokJAAAJCQrJSQAAAAAAAAAACQkJCQqJCQkTk9OeXl5eZ2kztXW1s/V1tXPz9bWeoGBgYGsgVdXV4GBgVdWViwrVjIsVlZWVissLILXs62tgzQJCgoKCgoKCgoKCgoKCgoKCjMzMzMzLS0tVwEBACUBAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAr19fQpKXX19fQq8/Ppc+lz9bQz9bQz6SkgHl5T09PTyQkJAAkJCQkJCQkAAAAJCQkJAAAAAAAAAAkJCQkJCskKiROT09OeXl5eaSkz8/W1dXW1s/P1teBgYGBgYGBgYGBgYGBgoFXVlYsKysrVlZWVixdrdetra1fNAkKCgoKCgoKCgoKCgoKCgoKMzMzMzMzLCxXAQEAJQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE+srHp619fXz6vQ0NDQq6XW1tDP1s+rpHp6eU9PKiQkJCQkJCQAAAAAAAAAAAAkJCQkJCQkJAAkJCQkJCQkKitOTk5OT3N5eXl5naSkz8/Pz9XW1c/W16WBgYGBgYFXV4GCgYGBgYFXViwsVlZWVlYsV63Xs62tiV8KCQoKCgoKCgoKCgoKCgoKCgozMzMzMzMsLFcrKwArAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVtCletfX19Clz8/W1s/P1tbQq8/Pz6Wkenl5T08kJCQkJCQkAAAAJCQkJCQkJCQkJCsrKyQkJCQrKyQkJCQkKyROTkhOeZ6eeZ2kpKTIz8/V1c/Vz9bW1oFWVlZWVleBgoGBgVeBgYGBV1YsVlZWKyyI19ezra2JXwkKCgoKCgoKCgoKCgoKCgoKCi0zMzNXV1csVywsACsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACSB0IDQ0NDQeqXPz9bWq9bQ0Kulpc/PpXp5eXlPJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCsrKysrKysrJCQkJCQqJE5PTnN5np55eaSkyMjPz8/Pz9bP1tbXrIGBrIiBgoKBgYGCgYGBgYGBgVdWVlYsV9fXs62trYlYCQoKCgoKCgoKCgoKCgoKCgoKLS0zM1dXVyxXVlYAKwAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAK6WBgKuA1qWkq6TQz8/W1s+lpaSlq6ukenl5T08kJCQkJCQkJCsrKysrKysrKyskJCtPT09PTysrKyQkJCQkJE9PT09Pc3mdnZ15pKSkyM/Pz9XP1tXW1tbXgYGBgVdWV11dgV2BgYGBgYGCXVYsLCyt17Otra2JgzQJCgoKCgoKCgoKCgoKCgoKCgozMzMzMzMzLSxXVwArAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAArq3rQes/WpXp6pM/Pz9bWpaWkpKWlpaR6eXlPJCsrKyskJCsrKysqJCtPT09PT09PT09PT08rKysrKyQkJCQkK09PT09PeXl5nZ2do6TPz8/P1dXV1tXX1tbQ0IGBgYFWV4GBgYGBgV1WV1dWViwsXdezs62ts4lfNAkKCgoKCgoKCgoKCgoKCgoKCjMzMzMzLS0sV4GBAAAAAQAAAAAAAAEAAAAAAAAAAAAAAAEAAFasq6V61qV6enrPpdDQ1qWkpHqlpaSlpHp5eU4kKyQrKyoqKiQkJCQqK09PT09PT09PT09PTysrK09PT08kJCQqT09PT05zeXmdeZ2jpM/Pz8/P1dXWz9fW1tfXpYGBXYGBgl2BXYGBgVZXV1dWV1et17Otra2tg18KCQoKCgoKCgoKCgoKCgoKCgoKMzMzMzMtLSwsgoIlAAEBAQEBAAABAQAAAAAAAAAAAAAAAQEAetbWpaTQenp6pKur1talenl6pKWlpKWkeXlPTyokKioqJCoqJCQkK09PT09PT09PTypPT09PT09PT09PT09PJCRPT09PTnN5eZ2dnaOkyM/Pz8/Vz9bV1tbP19fXVlddgV1XV1ddgYGBgYGBXSyCgrOzra2ts62DXwoKCgoKCgoKCgoKCgoKCgoKCgozMzMzMzMtLCyCgisAAAEBAAAAAAAAAAAAAAAAAAAAAQEBACWB1qWAq6t5eXmlpNDPz3p6eXqkpKSkpKR5eU4qJCoqJCQrKiskKitPTypPT09OKk9PKipOTk9PTysrKiQkKiokJE9PT09Oc3l5nZ2jo6Okzs/Pz9bVz9bW18/Pz9esVl2BgYFXV1aBgoFXV4EyV62trbOtra2ziYM0CgoKCgoKCgoKCgoKCgoKCgoKCjMzMzMzMy0sLIKCKwAlAQABAAEAAAAAAAAAAAAAAAAAAAAAK4GsgHmkpU95eqWl0KSkeXp5gKSkpKSkpHpPJCQkJCQkJCskJCQrTyoqT04qKk5OTioqJCoqKk9PTytPKiQkKiokTk5PT05zeXl5pJ2jpKTIpNbV1tbP1tbW1oCA0NeBV11XV1aBgYGBgYFdViyC19etra2Jra2JXzQKCgoKCgoKCgoKCgoKCgoKCgoKMy0zMy0tLS0sgoIsACUBASUBAQEBAQEBAAEAAAAAAAABAAArrKuBeqR6VXl6pKTPeXl5enqAeqR6pHp6ek8kJCQkJCQkJCQkK09PKipPJCQqTk9PT04qKiokT09PKipPKiokKipOTk9PT3N5eXmknZ2kpKSj1dXW18/P1tbWenql19d6V4GsrKyBgVaBgVcsV63X162tra2zrYNfNAoJCgoKCgoKCgoKCgoKCgoKCgozMzMtMzMtLCyCglYAAQEBAQEBAQEBAQEBAQAAAAAAAAAAAFbXq3p5gHp5eoCkpKV5eXl6enp6gHp6enp6TyQqJCQkJCQqJCpPTyoqTyokKk5PTk5OTioqKipPT08kKk9OKiQkKk9PTk9Pc3l5eZ2dnaTIo6PP1tbW1c/W1talpYCr19ClgYFWgYGBV1eBLFets62tra2JrbOJg180CQoKCgoKCgoKCgkKCgoJCgoKClczLTMzLS0sLFdXVwABAAEBAAAAAAABAQAAAQAAAAABAQAAT6zWgHqkenqlenqAgHl5enp5VXp6gHl5eXl6KiQkJCQkJCQkKk9PTk9PTioqTk9PT05PTk5OTk9PTyROT05OJCQqT09PT09zeXmdnZ2dncikpM7Pz9bWz9XW1qWlgYGs11ZWXYGBgYGBgVcsgrOtra2tra2trYmDWC4JCgoKCgoKCgoKCgoKCgoKCgoKXlczLS0tLSwsV1dXAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAArVtCAenpPenp6VXp6eXl6eXlVenp6eXlPT3pPJCQkKioqKiQqT09OT09PTk5OTk5PTk9OTk5OTk9OT09PTk4kJE5PT09Pc3N5eZ2knZ2dpKTIyMjP19bV1c/XgYFWgYHQ14GBgYFWV4GBLCyts62tra2trbOtiV80CgkKCgoKCgoKCgoKCgoKCgoKCgqJXlczLS0sLCxXV4EAAAAAAAAAAAAAAAAAAAAAAAAAACtPgVZPrIB6ek96enpPenp5eXl5eU96enl5eU8kT3okJCQkT09OKk5PT09PT05OTk5PT05PT09PT09PT05PT09OTk5OT09PT09zc3l5nZ6enXmkpKTPzs/P1tbWz9erq4GBe4HQrFaBXYFXXYEsV62zra2tra2trYmJXzQKCgoKCgoKCQoKCgkKCgoKCgoJComtXlctLSwsLFdXgQAAAAAAAAAAAAEAAAAAAAAAAAAAVlZWgSuAgXp6T4B6T096enl5eXl5VYB6enl5ek9Pek8kJCpPT04kTk9PT09PTk9PT09PT09PT09PT09PT09PT05OTk9PT09PT3N5eXmdnZ6dc56kpMjPz8/Pz8/P1tDQgYGBgYHXgVZXVldXgSyCrbOtra2tia2tiYNfNAkKCgoKCgoKCgoKCgoJCgoJCgkKgoOtglctLSwsVlZXAAAAAAAAASUrKyslJSslAQEBKytWrFZPVnqAgKVVgHpPT3p6eXl5VXl6enp6eVV5T05PeSokT09PJCpOT09PT1VPTk5PT09PT09PT09PT09PT09PTk9OT09PT05Pc3N5eZ2ennl5np6dpM/Pz8/Pz8/Q19eBgYGBgdHXrKysgoFXLIKtra2tra2JiYmJg180CQoKCgoKCgoKCgoKCgoKCgoKCQpeXoOtgi0tLCwsLIErJSsBAQAAAAABAQEBAQErKysrK1aBpYFWgYGBrHp6ek9PeXp6elVVelV6enl5VVVOTipPTyRPTk4qTk9PT09PT09OTk9PT09PT09PT09PT09PT09OT09PT09PTk9zc3l5nZ6enXmenqSkz8/P1tbQz9DW1oGBgVeBgazXgYGCgVdXgq2tra2trYmJrYmDXgoJCgoKCgoKCgoKCgoJCgoJCgoKCl5eWIKtXi0sLCwsVywsLCwsLCwsLCwsAQEBAQcrKywsLCt7gVZPelaAgYB6VU95enp6enp5VXp5eXlPVU5OKk5VT09OTk5OT095T09PT09OT09PT09PT09PT09PT09PT09PT09PT09OT3N5eXl5np6eeZ2kpKTPz8/W1tfW1tDQgYGBgV2BgayBgYGCgVeIs62tra2tra2tiYM0CgoKCgoKCgoKCgoKCgkJCgoKCgoKWFheV4KtVywsLCyBViwsLCwtMy0zMzMzAQErKwcHKysrAXvXrKVWKyt6enp6T3p6enp6eXp5gHlVek9VT04qKk9PT05OTk5OTlVPT09PT09PT09PT09PT09PT09PT09PT09PT09PT05OT3l5eXmepJ55naR5nc/Pz8/P0NDQ1taBgYGCgoGBrIGIra1XV4mzra2tra2trYmJgzQKCgoKCgoKCgoKCgoKCgoKCgoKCgpYWF5YV4KCLSwsLIJXLC0sLS0tLS0tLDNXLCwzV1csKysBrNfX19fQ16xWVnp6enl5eXl6enp6T1V6VVVPKioqT09PT09PT09PVU9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09zeXl5nZ6keXmepHmkz8/Pz9bP0NbW1oGBgYKsgoGBgoNYLQhXrbOtra2tra2tiYlfNAoKCgoKCgoKCgoKCgoKCgoKCgoKClhYV1hYWF5YLSwsglczMzMtLC0sLVeCiVczM1deXoIrKwGB16zR19esrKaBelVVeXp6eXp6VXpPVXp5VVVPT09PT09PT09OTk5PVU9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT3l5eXmenqR5eZ6eeaTPyM/P1tfW0NfXrFeCgYJdV4leCQkuLF6ts62tra2tra2Jg140CgoKCgoKCgoKCgkJCgoKCgoKCgoKV1hYWFhYWINXLCyCVzMzMy0zWIKJiV4zLVczV1hYg1cBAIHXrKyBgVZWeoGBelV6enp5enp5ek9PenpVT09OT09PT09PT05OTk95T09PT09PT09PT09PT09PT09PT09PT09PT09VT09PeXl5eZ6knnl5pJ55pM+kz9bW16vW19esgYGBXYGJNAkKLi0tXq2zra2tra2trYmDWAoKCgoKCgoKCgoKCgoKCQoKCgoKCgozV1dYV1hYXoIsLF5eLVheiYleWDMtM15eVzNXg4OtgisAVtfX19fX19fXrFZ6enp6elV6enp6VVV6ek9PT05PT09PT09PT05PT3lPT1VPT09PT09PT09PT09PT09PT09PT09PT1VPT095eZ6epKSeeXmknXmkz6TP1tbXetCsrIGsgVeIXi0uCS4uLi1erbOtiYmJra2JiYM0CgoKCgoKCgoKCgoKCgoKCgoKCgoKCjMzM1dXV1hXXldXV4JeXlgzM1dYXl5eVzMzWF6JibOCLAAAK6zX19esrKysK3p6ek9PVXp6enpPVXp6T1VPJCpPT09PT09PTypPT09PeU9PT09PT09PT09PT09PT09PT09PT09PeU9PT3l5np6eeZ55nqSdeaTIyM/Q1taA16ysVoGIrVgJCS4KCgotLV6tra2JiYmtrYmJXzQKCgoKCgoKCgoKCgoKCgoKCgoKCgoKLS0zMzMzM1dYXl5egjMzWF6CXl5YMzNXWF6DiYmJs15XJQAAACUrKyUAACQrenp6Kip6enp6ek9VeXpPT08kKytPT09PT09PTk9PT09VT09PT09PT09PT09PT09PT09PT09PT095T09zeZ6kpJ6eeZ6kpHl5pMik0NDW0KXXpaV7gYk0CQkuLgoKCgktgq2trYmJia2tiYleNAkKCgoKCgoKCgoKCgoKCgoKCgoKCgotLS0tMzMzM1dYWIKJV15YWDMzWFhYXl5fiYmzs7OzXoIrAAAAJSsrKyUAK1V6elVPT3p6gE96T1VVek9PTyQqK09PT09PT09PT09PT1VPT09PT09PT09PT09PT09PT09PT09PT3l5eXl5np6eeXmeeaSkeZ2kpKTQ1talgdaBga2JCQkJCgoKCgoKCTOCra2tiYmJra2Jg1g0CgoKCgoKCgoKCgoKCgoKCgoKCgoKCi0tLS0tLS0tLTMzgq1XM1dYWFhYWF6Dg4mJs7Ozs4leXisAAAArKysrKyUlK4FWT1VVeoB6KnpPeVV6T09PJCQrT09PT09PTypPT09PeVVPT09PT09PT09PT09PT09PT09PT09PeXl5eXqenp55eaSepJ55nqSkpNbX1qWs162tXgkJCgoKCgoKCgoJM4Kts62JiYmtiYlfNC4KCgoKCgoKCgoKCgkJCgoKCgoKCgoKLCwsLCwsLS0sLCxXrVdXV1heg4mJra2zs7Ozs7OzgzMsKwAAAAAlKyUBACtWgVZPenqApSpPek9VT3pPT08qJCtPTysrTytPKk9PT095T09PT09PT09PT09PT09PT09PT09PT095eU95ep6kpHqepKSeeXmkyKTP1qvQpdfXV1cJLS4KCgoKCgoKCgkzV62zrYmJia2JiV40CgoKCgoKCgoKCgoKCgoKCgkKCgoKCgosLCwILCwsLAgICCyIV1dYXoOJs7Ozs62JiYmDXl4tCCwBAAAAAAAAAAAAJHqAVVWAgKV6JHp6T09Pek9PTyskKytPKytPK08rT09PT3lPT09PT09PT09PT08qT09PT09PT09PeXl5T3menqSkpJ6kpKR5eaTIpNDX19esrFctLQkuCgoKCgoKCgouCVdXrbOtia2trYmJXjQKCgoKCgoKCgoKCgkKCgoKCgoKCgoKCiwsCAgsLCwIAgEBAVeCVzNeXomJiYmDWDMtCQgCAgIsLAAAAAAAAAAAAAArenpVeqWlgE9WenpPT09VT09PKyQrK09PTysrKysrK09PT09PT09PT09PT09PKiRPT09PVU9PT3l5eXlPeZ6epKSknp6kpHl5pKSk1tfX19dWWDMzCTQuCgoKCgoKCVkJV1ets62Ira2tiYM0NAoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCAgILCwsLCwCAgICLIgzLTNYXlhYLQgCCDOCgldXLCwBAAAAAAAAAAAlUCtWVlWlpaVPT3pVek9PT09PT09PJCorT09PKysrKyQqT09PT09PT09PKipPT09PTk9PT095T09VeXl5eXl6pKSkpKR6np6knqTJpM/Wq4DXrFCsra2CLQkKCgouCQlfiQhXV62zrYKtra2JgjQ0CgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoICAgILCwsLCwsLCwsgiwsLCwsLCwtV4KIrIJXAQEBAQAAAAAAAAEBKyuBVk8rgIF6ek96T1V6T09PT09PT08kJCtPKysrKysrKypPT09PT09PT09PT09PT08qT09PeXl5c3l5eXNPeZ6kpKSkpKSkpHl5pM+kz9arpdasLKyIiIKJMwkJCQkJg60tCFdXra2tgomJrYleNC4KCgoKCgoKCgoKCgoKCgoKCgoKCgoKCggICAgsLCwsLCwsASuBASwsLCwzV1dXLCwBAQEBAQEHKysrBysBAQElKyyBVnrXpU9PT3pPenpPKk9PT09PTyskKytPTyorK08rK09PT09PT08qT09PT09PKk9PT095eU95enl5T3mknp6kpKSenqSkeZ2kz6TW16uBgayCey0tAi2DMwkJLdetLS0sV1eJs62CiYmtiVg0CgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCAgsLCwsLCwsLCwBLFcBLCwsLCwsAQEBAQEBAQEBAQErKysrKyxWAQErKyuBrIHRrKxWVVZ6TyQqT09PK09PTyQkK09PKiokJCsrT09PT09PT05PT09PT09OT09PeXl5eXl6eU95pHmkeqSkpJ6epKR5pKTPpNbX1tfX19fXra2CLIJeCVfXiS1YLSxXV4izrYOtrYmJMzQKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoBASwsLCwsLCwsLAEsLAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBASsBAQErK1BWK1bX19dWe4F7VlZWVlZPT09PJCRPVlYrJCQkACQrT09PVU9VT09PT09PT09PT095enlPeXp5eaR5eaR5pKSkeZ6keXmkpMjO1tfQ19espaysrNfX16yC11gJCTQtLFdegq2tgomJiYMtLgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgEILCwsLCwsBwEBKywBAQEBAQEBAQEBAQEBAQEBAQEAAAAAAAAAAAEAAQEBUFYrLFZWrFYAASsrLFZWVlZWVlZWVlBWVoGBV1ZWUCsrK09PTyskKipPT09PT09PT3l6eU9Penl6eXN6pHqkpKSepKR5nqSkyM/W16ulq6WBgYGBrKzX19eCLC1YNC0sV15Xra2Cra2JgwkKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKASwsLCwrAQEBAQEsLAEBAQEBAQEBAQEBAQEBAQEBAQEAAAAAAAAAAAAAACtWVlZWVlYsLFYrAAAAAAAAAAABJSsrKwEBKyssMlZXV12BgVdWVisrKysrT08rK09Pek9PT3N5enpPeXqepKSkpJ6keXmkpKSkz9bWq3qr19fX19fQ19es19fXWC0tLSxXglezrYKJiYleCQoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoHKywsKwEBAQErKywBAQEBAQEBAQEBAQEBAQEBAQEAAQEBAQEBAAAAAAErKysrVlYrKytX16wrAAAAAAAAAAAAAAAAAAAAAAAAAAEBKysrLFZWV4GBgYFXV1ZWVlZWT09PT3qkeXl5enmkpKSkpKR5eaSkpM/P1tbW19fX19fX19fXgStQrNfXgi0tLFeCV7OtgomJiTQJCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgErKysrAQEBASsrKwEBAQEBAQEBAQEBAQEBAQEBAQAAAAAAAAAAAAABAQEAKytWVgAAK1ZWXVYAAAAAACslJQEAAAAAAAAAAAAAAAAAAAAAAAABASsrLFZWVleBgYGBgYF6enpPT3meeaSkpKSkeXmepKSkz8/W1tfX19fX19fX189WV4JQgtfXrCwsV4KCra2CiYmDCQkKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKASsrKwEBAQEBKysBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAAAQEAAAAAAAAAJSslJCQrASwrMqyBKwAlJSUrKysrAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAQErKyxWXYGBrKylgYF6pKSenqR5eZ6kpMjPz9bX19fX19fX19fX14F8WFcsgdfXLCxXgoKtrYKJiYICCQoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoBKywrAQEBASsBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAQEAAAAAKyUAAAABAAAAAAArKyUsKwFWgawyAAAlKysrKysBAQEBAQEAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAABysrVl2BrKysrKWlpHp5pKTIyMjP1tfX19fX19fX19fX19FXVy0r0dcsJSxXgq2tgomJWAIKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCisrKwEBAQElKwEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAAAAAAKyUAASsrKyUAACUlK1YBKysrV11WAAAAAAAAASsrKysrKysrKysrACsBAAAAAAAAAAAAAAAAAAAAAAAAAAAAACUrLFZdgoKsrKys0NbPyNXW19fX19fX19bW1tbX19dXLSzX1yslUVeCra2CiYkzAwoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKASsBAQEBASsBAQEBAQEBAQEBAQEBAQEBAQEBJQEBAQEAAAAAAAAAKyUlJSsrVnsrAAAlACslASwrVq2CKwAAAAAAAAAAAAAAAAErKysrLFZWViwsKysBAAAAAAAAAAAAAAAAAAAAAAAAAAEBASssV4Kt19fQ1tbX1tbW1tfX19fX19fX1qx7gdfXKywzV4KtrYKJiQkDCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAQErJSUBAQEAAAAAAAAAKwElKysrgYAAAAAAKwArKysrLIGsgVBQKysrAAAAAAAAAAAAAAAAAAErKytWVlZWVlYsLCsrKysrKwAAAAAAAAAAAAAAAAAAJStWgazX19fX19fX19fX19fX19fX16zX19clLCyCgq2tgoODAgkKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgEBASUBAQEBAQEBAQEBAQEBAQEBAQEBKysBASsrKyslKwEAAAAAAAABJQErKytWelZWVSslKysrKysrK1aIrIFWVoFWVk8rKysAAAAAAAAAAAAAAAAAASsrKytWVlZWVlZWVlYrKysAAAAAAAAAAAAAAAAAKytWptfX19fX19fX19fX19fX19fX1yUsLIKCrYmDXl4CCQoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKAQEBAQEBAQEBAQElAQEBAQEBAQEBASsAJSsAASsrKyUlKwEAAAAAAAAAAQArKytWKytWVgABACsrKysrKytWgoKBgSsrKysrK1ZWKwAAAAAAAAAAAAAAAAAAAAAAJSssVlZWVlZWVnpWTyskJAAAAAAAAAAAAAArK1aB1tfX19fX19fX19bW19fWJSwIV4KtiYIzMwIJCgoKCgoKCgoKCgoKCgoKCgoKCgkKCgoKCgoBAQEBAQEBAQEBAQEBAQEBAQEBAQElKysrKwAAAQErKyUrJQAAAAAAAAAAAAArK09PT1Z6AAAAACUrKysrKysrVoGsgoIrKysrVislK08rAAAAAAAAAAAAAAAAAAAAAAAAACsrVlZWVlZWeqWlgVYrAAAAAAAAAAAAJStQeqvW1tfW1tfWz9bW1Z4kLCwsV62Igi0tAgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgEBAQEBAQEBAQEBAQErAQEBAQEBASsBAAErAAAAAAErJSsrJQAAAAAAAAAAACUrK1ZWVoArAAAAAAArKysrKysrKyxdXYKsgVZWACQkK08rKysrKyUrAAAAAAAAAAAAAAAAAAAAACUrVlZWVlZWeqXQq08rAAAAAAAAAAAlK1ZWgdDP1tbX1s/IeSUmLCxXrYNYCAgDCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKAQEBAQEAAQAAAAABAQEBAQEBAQEBAAAAAAEBAAAAACUrJSsrJQAAAAAAAAAAACUlVlZWelYAAAAAAAAAKysrKysrKysrK1aBrKxXVisAJCsrT08rJVZWT09VVSskAAAAAAAAAAAAAAAAACtQUFZWVnqBenqlpE8kAAAAAAAkJSUlT4Gsz8/W1tZ6ASUsLDOtiTMCAgkKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoBAQEAAAAAAAAAAAAAAAElAQEBKyUBAQAAKwEAAAAAACUrJSsrAQAAAAAAJQAAACUrK1Z6TyQAAAArKwAAJCsrKysrKysrJSsrVoGsrIErJQArKysrKyskJFWAT09VelYrKwAAAAAAAAAAAAAAACUrVlZWVnql0NbPTyQAAAAAAAAAACt6rNDP0E8BASYsM4OCLAICCQoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgEBAQAAAAAAAAAAAAAAACUBAAABKyUBAAABAQAAAAAAACslJSsrAQAAAAAAAAAAJSUlK3pVKwAAAAArAAAAAAAAKysrKysrKwEAAStWgYKBgU8AJCtPKyQkVXpVT1V6eoCBgHpVKwAAAAAAAAAAAAAAACtWVlZ6pdfX16UrAAAAAAAAAAAre6zQKwEBASwzgjMCAgIJCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKAQEAAAAAAAAAAAAAAAAAASUBAAAAKysrAAABAQEBAAAAASsrJSsrAAAAAAAAAAAAKyskVlYrKyUAACsAK1YrAAAAASUlJQEBAQEAAQEBK1aBgYErKysrJCRVVk9Penl6VXqAgIB6gHpWTyQAAAAAAAAAAAAAK1BWVoDQ19eBKysAAAAAAAAAK4ErAQECLDNeLAICAgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoBAAAAAAAAAAAAAAAAAAABASUBAAAAACsrKwEBAQEAAAAAACUBASsrAAAAAAAAAAArK09PTysAJQAAKwBPVoBWTyQAAAAAAAAAAAEBASUBJSsrVoFWKysrK1VVT1VVenlPT3qAenqApM/PpaWleisAAAAAAAAAAAArVlaBrKzW1qVWAAAAAAAAAQEBAQEsM1gIAgICCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCg=="
;
//-----------------------------------------------------------------------
//                VARIABLES  GENERALES
//-----------------------------------------------------------------------
var counterInterval; var momoregular;var boutton;
var x = g.getWidth() / 2; var y = g.getHeight() / 2;
//var img="";
var fic; var T; var lit_img=0; var fic_img=["mote2","mote1","mote3","moto1","moto2"];
//-----------------------------------------------------------------------
//                FONCTIONS UTILITAIRES
//-----------------------------------------------------------------------
function Tsleep(ms) { var ok="0"; var debut=Date.now();
  
  while (ok=="0") {  
    if (boutton ==1 ) { ok="1"; boutton=0;} else { if Date.now();-debut < ms ) {ok="0";} else {ok="1"; } }
  }
}

function Tsleep_Led(ms,led,etat) {   var change=0; var ok="0"; var debut=Date.now();
 
  while (ok=="0") {
    
     // TEST FIN
     if (boutton ==1 ) { ok="1"; boutton=0;}
     else { if (Date.now() < ms ) {ok="0";} else {ok="1"; }  }
    
    // BOUCLE + LED    
    if (change==0) { if (etat==1) {  change=1; if (led==1) {LED1.write(1);} else { LED2.write(1);}  }}
    else { change=0; if (led==1) {LED1.write(0);} else { LED2.write(0);} }

    Tsleep(500);
  }
}
  
//--------------------------------------
//-------FCT -AFFICHAGES ----------------
function set_Aff() { g.clear(reset); Bangle.drawWidgets(); g.setFontAlign(0,0); g.setFont("Vector",40); g.setColor(0,0,0); }

function lit _fic (i) { fic=fic_img[i]+".raw"; console.log(fic,"Lecture"); img=require("Storage").read(fic); console.log(img.length); }

function D_ecran(img,x,y,T) { g.clear(); g.drawImage(atob(img), x, y, { scale: T }); }

// ---------------
function aff_momoregular () { if (lit_img==0) { img=lit_fic(4);lit_img=1;} D_ecran (img,0,24,1); }

//-------------------------------------------------------
// temperatures pression, altitude 
//
var history_T = [];var history_P = [];var history_A = [];
var temperature;var pression;var altitude;
var data;

function acqui_press() { Bangle.getPressure().then(data => { suite_press (data); });}
 
//------------------------------
function suite_press(data) {
  var temp=data.temperature; var rect_temp=-6.5;
  var press=data.pressure;  var rect_press=0;
  var alti=data.altitude; var rect_alti=62;
  
  // moyenne de 5 temperatures
  while (history_T.length>4) history_T.shift();
  history_T.push(temp); temperature = E.sum(history_T) / history_T.length; temperature +=rect_temp;
  
  temperature=temperature.toString();
  var point=temperature.indexOf(".");
  if (point==0) { point=temperature.length;temperature = temperature.substring(0,point);}
  else { temperature = temperature.substring(0,point)+"�"+temperature.substring(point+1,point+2);}
  //console.log("Temp:",temperature);

  // pression  : moyenne de 5 
  while (history_P.length>4) history_P.shift();
  history_P.push(press); pression = E.sum(history_P) / history_P.length; pression +=rect_press;
  
  pression=parseInt(pression)+0;
  //console.log("Pression:", pression);
  
  // altitude : moyenne de 5 
  while (history_A.length>4) history_A.shift();
  history_A.push(alti);  altitude = E.sum(history_A) / history_A.length; altitude +=rect_alti;
  
  altitude=parseInt(altitude)+0;
  //console.log("Altitude:",altitude);
}

//------------------------------------------------------

var calendar = []; var current = []; var next = []; var event =[]; var titre;
var nb_heures; var nb_minutes;

function updateCalendar() {
  calendar = require("Storage").readJSON("android.calendar.json",true)||[];
  calendar = calendar.filter(e => isActive(e) || getTime() <= e.timestamp);
  calendar.sort((a,b) => a.timestamp - b.timestamp);

  current = calendar.filter(isActive);
  next = calendar.filter(e=>!isActive(e));
}

function isActive(event) {
  var timeActive = getTime() - event.timestamp;
  return timeActive >= 0 && timeActive <= event.durationInSeconds;
}

function zp(str) {
  return ("0"+str).substr(-2);
}

function timeToNext() {
  if (next.length !=0) {
     //var inter=next[0].timestamp-getTime();nb_heures=Math.floor(inter/3600);nb_minutes =Math.floor((inter-3600*nb_heures)/60);
     var tempo=new Date(next[0].timestamp*1000); nb_heures= zp(tempo.getHours()); nb_minutes=zp(tempo.getMinutes()); titre=next[0].title;
  } 
  else { nb_heures=0; nb_minutes=0; }  
}

//-------------------------------------------------------------------------------------------
//                AFFICHAGES 
//-------------------------------------------------------------------------------------------
var altern=0;

function aff_principal() { ecran=1; set_Aff();

  //
  // --------- HEURE et MINUTE ------------------
  //
  var hh=new Date().getHours().toString(); var aff=hh+":";
  var mm=new Date().getMinutes().toString(); if (mm.length==1) { aff=aff+"0"; } aff=aff+mm;
  
  //  rectangle rouge/blanc 
  if ( altern==0 ) { g.setColor(1,0,0); g.fillRect (2,28,172,108); g.setColor(1,1,1); altern=1; } 
  else { // Blanc bleu
    if (altern==1) { g.setColor(0,0,1); altern=2; } 
    else { // blanc/rouge 
          if (altern==2) { g.setColor(1,0,0); altern=3; }
          else { // noir bleu clair
                g.setColor(0,0,0); g.fillRect (2,28,172,108); g.setColor('#00F0FF'); altern=0;}
         }
  }
  y-=11; g.setFontAlign(0, 0).setFont("Anton").drawString(aff, x, y); 
  
  //-----------------------------------------------
  //       JOUR MOIS 
  //
  var jourSem = ""; var calWeek = false;

  jourSem = require("locale").dow(Date(), calWeek ? 1 : 0); deb=jourSem.substring(0,1); deb=deb.toUpperCase(); jourSem = deb+jourSem.substring(1,3);
  // DATE MOIS 
  var dateOnMain = "Long"; var dateStr = (dateOnMain === "ISO8601" ? isoStr(Date()) : require("locale").date(Date(), (dateOnMain === "Long" ? 0 : 1)));
  var jourMois= dateStr.substring(0,2); 
  var blanc=dateStr.indexOf(" "); var mois =(dateStr.substring(blanc,dateStr.length)).substring(0,4);

  g.setColor(0,0,0); // noir
 
  x+=4; y+=55; dateStr=jourSem+"        "; g.setFont("8x12",3); g.drawString(dateStr, x, y);
  x+=40; y+=1; dateStr=jourMois+"    ";  g.setFont("Vector",40); g.drawString(dateStr,x,y);
  x+=6; y+=0;  dateStr=mois.toUpperCase(); g.setFont("8x12",3); g.drawString(dateStr,x,y);
  
  //-----------------------------------------------
  //           CALENDRIER 
  updateCalendar(); 
  timeToNext();
  x=5; y+=32;
  if (nb_heures!=0 || nb_minutes!=0 ) { calen=nb_heures+":"+nb_minutes+" "+titre;}  else { calen= "sans elements" ;}
    
  g.setFont("Vector",20);
  g.setFontAlign(-1, 0);
  g.drawString(calen,x,y);
  
  if ((nb_heures==1) && (nb_minutes==0)) {Bangle.buzz(1000);}
  if ((nb_heures==0) && (nb_minutes==30)) {Bangle.buzz(2000); Tsleep(1000);Bangle.buzz(1000);}
  if ((nb_heures==0) && (nb_minutes==30)) {i=0; while(i<4) { Bangle.buzz(500);Tsleep(500);i+=1 } }
  
  //  ----  generiques

  acqui_press();
  
  if (var momo_rep => 3) { aff_momoregular(); momo_rep=0; Tsleep(8000); } else { momo_rep +=1;}

}

//-----------------------------------------------------------------------

function aff_second() { ecran=2; set_Aff();

  console.log("affichage second");
  g.setFont("Vector",24);  g.setFontAlign(-1, 0);
  
  var batt=E.getBattery().toString()+ "%";
  y=40; g.drawString("B:"+batt, x, y);
  y+=30;g.drawString(" T:"+temperature, x, y);
  if (pression-1013>=0){tend="Beau "+pression-1013;}   else {tend="Mauv "+pression-1013;} y+=30;g.drawString("Prs:"+pression+" "+tend, x, y);
  y+=30;g.drawString(" Alt:"+altitude+" m", x, y);  
  
  Tsleep_Led (5000,1,1);
}

//-------------------------------------------------------
//          PAGE CALENDRIER 

function fait_titre(titre) {
  if (titre!="") { if (titre.length>10) { titre=titre.substring(0,10); }  }
  console.log(titre,titre.length);
  return titre;
}

var Haut=24; var inter=0;

function drawEventHeader(event, y) {

  g.setFont("Vector", Haut);

  var time = isActive(event) ? new Date() : new Date(event.timestamp * 1000);
  var timeStr = zp(time.getHours()) + ":" + zp(time.getMinutes());

  y += 0; x=5;
  
  if (isActive(event)) {
     g.drawString(zp(time.getDate())+"." + require("locale").month(time,1),x,y);
  } else {
    var offset = 0-time.getTimezoneOffset()/1440;
    var days = Math.floor((time.getTime()/1000)/86400+offset)-Math.floor(getTime()/86400+offset);
    if(days > 0) {
      //g.setFont("Vector", 24);
      var daysStr = days===1?/*LANG*/"Demain":/*LANG*/"J+"+days;
      g.drawString(daysStr,x,y);
    }
 }
  g.drawString(timeStr, 100, y);  
  y+=Haut+inter;
  return y;
}

function drawEventBody(titre,y) {

  //console.log(titre,titre.length);
  x=3;
  g.setFont("Vector", Haut);
  if (titre != "") {
      g.drawString(titre, x, y);
      y+=Haut+inter;}
  return y;
}

function drawEvent(event,titre,y) {
  //console.log(" y deb ",y);
  y = drawEventHeader(event, y);
  //console.log(" y H",y);
  y = drawEventBody(titre, y);
  //console.log(" y B ",y);
  return y;
}

var curEventHeight = 0;

function drawCurrentEvents(y) {
  
  g.setColor(0,0,1);
  g.clearRect(5, y, g.getWidth() - 5, y + curEventHeight);
  curEventHeight = y;
  //console.log("y",y); 
  if(current.length === 0) {
    titre="";titre=fait_titre(titre);
    console.log("premi�re ligne");
    y = drawEvent({timestamp: getTime(), durationInSeconds: 100},titre, y);
  } else {
    y = drawEventHeader(current[0], y);
    for (event of current) {
      console.log("current");
      titre=event.title;titre=fait_titre(titre);
      y = drawEventBody(titre, y);
    }
  }
  curEventHeight = y - curEventHeight;
  return y;
}

function drawFutureEvents(y) {
  g.setColor(g.theme.fg);
  for (event of next) {
    console.log("futur");
    titre=event.title;titre=fait_titre(titre);
    y = drawEvent(event,titre,y);
    if(y>g.getHeight())break;
  }
  return y;
}

//-----------------------------------------------------------------------
function aff_agenda() { ecran=3;set_aff();
                       
  console.log ("troisieme ecran");
  
  g.setFontAlign(-1, 0); g.clearRect(5,24,g.getWidth()-5,g.getHeight());
  updateCalendar();
  y = 33;
  y = drawCurrentEvents(y);
  drawFutureEvents(y);
  
  Tsleep_Led (5000,2,1);
}

// ---------------
function aff_momo() {
  ecran=4;

  //lit_img=0;
  //for (i=0;i!=fic_img.length;i++) {
  //    img=lit_img(fic_img[i]);
      D_ecran (img,0,24,1);
      Tsleep_Led (5000);
  //}
}

//-----------------------------------------------------------------------
//                         PRINCIPAL
//--------------------                -----------------------------------

function aiguillage (){
  console.log("Boutton");
  // Pour arreter Tsleep 
  boutton=1;

  if (ecran==1) { aff_second();}
  else { if (ecran==2) { aff_agenda();} 
         else { if (ecran==3) { aff_momo(); }
                else { 
                       // Show launcher when middle button press
                       Bangle.setUI("clock"); }
              }
       }
}

//------------------
function general() {

  aff_principal();

  if (!counterInterval)
      counterInterval = setInterval(aff_principal, 60000);

  //if (!momoregular)
  //    momoregular = setInterval(aff_momoregular, 1*60005);
  
}

//--------------------     MAIN           -----------------------------------

Bangle.setBarometerPower(true);
setTimeout(general,15000);

setWatch(aiguillage ,BTN1,{edge:"rising", debounce:30, repeat:true});

acqui_press();
general ();

//aff_momoregular();


// Register hooks for LCD on/off event and screen lock on/off event
//Bangle.on('lcdPower', on => {   general(); });
//Bangle.on('lock', on => { general(); });

// Load widgets
Bangle.loadWidgets();

// end of file
